### ISSUE TITLE
NoClassDefFoundError when shutting down Tomcat

### ISSUE THREAD

**Issue by sgattani** [cobertura/cobertura#123]
Hi:

I am using cobertura 2.0.3 to instrument Java code compiled with JDK 1.7.0_25. I create a war file with the instrumented classes and deploy to Tomcat 7.0.50. The webapp starts up fine and I see the following during startup.
Jan 13, 2014 7:18:16 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
INFO: Cobertura: Loaded information on 3317 classes.
Jan 13, 2014 7:18:20 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler saveCoverageData
INFO: Cobertura: Saved information on 3317 classes.

Note, that I do include the cobertura jar in WEB-INF/lib folder
However when I shutdown tomcat I see the following exception and the .ser file does not get updated:

xception in thread "Thread-3" java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector$ApplyToClassDataLightClassmapListener
    at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:123)
    at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:107)
    at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:270)
    at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:32)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector$ApplyToClassDataLightClassmapListener
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
    ... 5 more

If instead I include the cobertura jar in tomcat/lib folder, I get the NoClassDefFoundError on my classes, which I am guessing cobertura needs to write data for!

Please advise how to proceed

**Comment by akuanyshev** [comment]
I have the same problem with cobertura 2.1.1. And I can't resolve this.

**Comment by liufang732** [comment]
I met the same problem with cobertura2.1.1, have you got any solution for it?

**Comment by akuanyshev** [comment]
No, I haven't

**Comment by liufang732** [comment]
I found solution for my problem today.  A cobertura-2.0.3.jar was added to my webapp\lib folder by mvn package.  When I removed this jar file and added cobertura-2.1.1.jar to tomcat\lib folder,  above problem not happen again.   So seems 2 jars with different version caused it.
