### ISSUE TITLE
Cobertura fails to generate report depending on the number of tests run and number of classes instrumented when Surefire forkMode=once

### ISSUE THREAD

**Issue by dsukner** [cobertura/cobertura#149]
Depending on the number of tests being executed and number of classes instrumented corbertura either succeeds or fails generating the report when surefire forkMode=once. With 82 tests run and 2778 classes instrumented the report generation is successfull, with 92 test and 2778 classes instrumented it fails with an EOFException ( see below). If forkMode=always everything is fine, however, then tests take too long to execute. Things I have noticed as part of the failure:
1. corbertura.ser doesn't get fully populated resulting in an EOFException upon generating the report
2. Wtih version 2.5.2 of the cobertura plugin the following lines get logged several times instead of once ... Notice that the final "Load" log statement is missing a corresponding "Saved".
   Cobertura: Loaded information on 2778 classes.
   Cobertura: Saved information on 2778 classes.
   Cobertura: Loaded information on 2778 classes.
   Cobertura: Saved information on 2778 classes.
   Cobertura: Loaded information on 2778 classes.
   Cobertura: Saved information on 2778 classes.
   Cobertura: Loaded information on 2778 classes.
   Cobertura: Saved information on 2778 classes.
   Cobertura: Loaded information on 2778 classes.
3. The same issue occurs with version 2.5.2 of the cobertura plugin + version 2.14.1 of the maven surefire plugin. 

pom.xml (snippet):

```
<profile>
    <id>cibuild</id>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cobertura-maven-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <maxmem>2048m</maxmem>
                    <formats>
                        <format>html</format>
                    </formats>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.17</version>
                <configuration>
                    <forkMode>once</forkMode>
                    <testFailureIgnore>true</testFailureIgnore>
                    <argLine>-XX:MaxPermSize=2048M -Xmx2048m</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>2.15</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>report-only</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>2.4</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.0</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cobertura-maven-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <maxmem>2048m</maxmem>
                </configuration>
            </plugin>
        </plugins>
    </reporting>
</profile>      
```

Log output: (sanitized snippet)

INFO: Cobertura: Saved information on 2778 classes.

Results :

Tests run: 92, Failures: 0, Errors: 0, Skipped: 0

[DEBUG] Executing command line:
[DEBUG] cmd.exe /X /C "C:\JDK64\LINKS\JDK6\jre\bin\java -Dlog4j.configuration=file:/C:/Users/SomeUser/AppData/Local/Temp/log4j3329423118774662460config.properties -Xmx2048m net.sourceforge.cobertura.reporting.Main --commandsfile C:\Users\SomeUser\AppData\Local\Temp\cobertura.7875981118856855982.cmdline"
[DEBUG] exit code: 1
[DEBUG] --------------------
[DEBUG]  Standard output from the Cobertura task:
[DEBUG] --------------------
[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[cobertura] DEBUG [main] net.sourceforge.cobertura.util.FileFinder - Adding sourceDirectory=[--source]
[cobertura] DEBUG [main] net.sourceforge.cobertura.util.FileFinder - Adding sourceDirectory=[C:\my_project..\my_project\src\main\java]
[cobertura] DEBUG [main] net.sourceforge.cobertura.reporting.Main - format is html encoding is UTF-8
[cobertura] DEBUG [main] net.sourceforge.cobertura.reporting.Main - dataFile is C:\my_project\target\cobertura\cobertura.ser
[cobertura] DEBUG [main] net.sourceforge.cobertura.reporting.Main - destinationDir is C:\my_project\target\site\cobertura

[DEBUG] --------------------
[DEBUG] --------------------
[DEBUG]  Standard error from the Cobertura task:
[DEBUG] --------------------
[ERROR] Apr 9, 2014 1:52:31 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
SEVERE: Cobertura: Error reading file C:\my_project\target\cobertura\cobertura.ser: null
java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2553)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1296)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at java.util.HashMap.readObject(HashMap.java:1029)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:479)
    at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at java.util.HashMap.readObject(HashMap.java:1030)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:479)
    at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at java.util.HashMap.readObject(HashMap.java:1030)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:479)
    at net.sourceforge.cobertura.coveragedata.CoverageDataContainer.readObject(CoverageDataContainer.java:321)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.loadCoverageData(CoverageDataFileHandler.java:84)
    at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.loadCoverageData(CoverageDataFileHandler.java:61)
    at net.sourceforge.cobertura.reporting.Main.parseArguments(Main.java:92)
    at net.sourceforge.cobertura.reporting.Main.main(Main.java:169)
Error: Unable to read from data file C:\my_project\target\cobertura\cobertura.ser

[DEBUG] --------------------
[ERROR] Error in Cobertura Report generation: Unable to generate Cobertura Report for project.
org.apache.maven.plugin.MojoExecutionException: Unable to generate Cobertura Report for project.
    at org.codehaus.mojo.cobertura.tasks.ReportTask.execute(ReportTask.java:93)
    at org.codehaus.mojo.cobertura.CoberturaReportMojo.executeReportTask(CoberturaReportMojo.java:232)
    at org.codehaus.mojo.cobertura.CoberturaReportMojo.executeReport(CoberturaReportMojo.java:356)
    at org.codehaus.mojo.cobertura.CoberturaReportMojo.executeReport(CoberturaReportMojo.java:252)
    at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:93)
    at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:68)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9:25.659s
[INFO] Finished at: Wed Apr 09 13:52:31 EDT 2014
[INFO] Final Memory: 29M/1135M
[INFO] ------------------------------------------------------------------------

**Comment by progosch** [comment]
We are experiencing the same issue. I tried your fix, but whole process slowed down (we doubled build time). Is there any fix that could help us to speed up a little bit?
I had tried multiple processes running in parallel (I mean a mvn cobertura:cobertura .... execution per Maven moduie), but it didn't help.
I appreciate any input.

**Comment by sush143** [comment]
**dsukner**  What is the path you specified under post build, after selecting the HTML Report option under trigger post build option
