### ISSUE TITLE
Error when using Java 8

### ISSUE THREAD

**Issue by sekotin** [cobertura/cobertura#166]
I'm trying to run Cobertura for Java 8 project. I get errors like

java.lang.VerifyError: Expecting a stackmap frame at branch target 78

Using -XX:-UseSplitVerifier does not help since I think it was dropped in Java 8.

**Comment by abbybader** [comment]
@dennisl I'm having trouble hitting the Maven plugin snapshots repo.  I've googled around for examples (haven't worked with Nexus in years) but I think maybe I'm just missing the appropriate <id> value.  Can you provide it?  I took a guess and ended up with the following:

    <pluginRepositories>
	    <pluginRepository>
        <id>codehaus-snapshots-group</id>
          <name>Codehaus Snapshots</name>
          <url>https://nexus.codehaus.org/content/groups/snapshots-group/</url>
	    </pluginRepository>
    </pluginRepositories>

**Comment by theHilikus** [comment]
@dennisl now that the issue is closed, is it just a matter of waiting for the 2.7 release of cobertura-maven-plugin??

**Comment by dennisl** [comment]
@theHilikus I am pushing first for a release of Cobertura, and after that a release of the Maven plugin.

**Comment by theHilikus** [comment]
makes sense. i just wanted to know what were the missing steps to having a working plugin. I was also assuming that Cobertura had already been released

**Comment by trothwell** [comment]
Do we have a date for 2.1 release?

**Comment by dennisl** [comment]
ASAP

**Comment by theHilikus** [comment]
Hi Dennis
I just tried cobertura plugin 2.7 after you (I think) sent an email to the maven mailing list; however, I still get a bunch of warnings. What am I doing wrong? or is java 8 not yet supported (I thought it was based on this thread)
I get two types of problems

```
[INFO] --- cobertura-maven-plugin:2.7:instrument (default) @ service-alarm-impl ---

mojoSucceeded org.codehaus.mojo:cobertura-maven-plugin:2.7(default)[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[WARN] Unable to instrument file /var/lib/jenkins/workspace/platform_HEAD/implementations/service/target/generated-classes/cobertura/com/foo/config/ServiceConfigPersistance.class
java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]
[WARN] Unable to instrument file /var/lib/jenkins/workspace/platform_HEAD/implementations/service/target/generated-classes/cobertura/com/foo/internal/config/ServiceConfigImpl.class
java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]
[INFO] Cobertura: Saved information on 12 classes.
[INFO] Cobertura: Saved information on 12 classes.

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.

mojoStarted org.apache.maven.plugins:maven-resources-plugin:2.7(default-testResources)[INFO] Using 'UTF-8' encoding to copy filtered resources.
```

The other error I see is too long to post all of it but this is the main part. It is related to lambdas

```
[INFO] --- cobertura-maven-plugin:2.7:cobertura (default) @ geckoflex ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 105 classes.
[WARN] JavaNCSS got an error while parsing the java file /var/lib/jenkins/workspace/platform_HEAD/implementations/blah/src/main/java/com/foo/CommunicatorImpl.java
ParseException in STDIN
Last useful checkpoint: "com.foo.CommunicatorImplcom.foo.CommunicatorImpl.CommunicatorImpl(SocketManager)"
Encountered " ")" ") "" at line 40, column 35.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...
    "false" ...
    "float" ...
    "int" ...
    "long" ...
    "new" ...
    "null" ...
    "short" ...
    "super" ...
    "this" ...
    "true" ...
    "void" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    <STRING_LITERAL> ...
    <IDENTIFIER> ...
    "(" ...
    "!" ...
    "~" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    "double" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    "double" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
```
Thank you for your help again

**Comment by dennisl** [comment]
The first problem I have not seen before. Could you please open a separate issue for that. If you could include a small test class that shows the issue, it would be very helpful.

The second one is not about the instrumentation or the calculation of coverage. The report should be ok despite the warning in the log. This is really about a problem in JavaNCSS, which is used by Cobertura. It is tracked in issue #220

**Comment by cromoteca** [comment]
I'm experiencing the same issue reported by @theHilikus, so I opened issue #248 for it.

**Comment by OhadR** [comment]
@dennisl  great job ;-) thanks. i have a similar issue with gradle-plugin, but i assume it is not cobertura's problem now, since 2.1 release.

**Comment by DINESHMOHAN** [comment]
Is there an ETA for Cobertura support for Java 8 ?

**Comment by klassounski-daitan** [comment]
Any news on the support for Java 8? Java 9 is coming out for god sake.

**Comment by madorb** [comment]
Java 9 is out :-)

**Comment by Ordiel** [comment]
I've literally been waiting this since first quarter of 2017 :/ I guess it was a good run... moving on to JaCoCo
