### ISSUE TITLE
Instrumented classes throw NPE during static initialization

### ISSUE THREAD

**Issue by netmikey** [cobertura/cobertura#172]
Hi there,

It seems that cobertura instrumentation "breaks" some of our classes. When we run the tests without Cobertura instrumentation, they succeed. Running them with instrumented classes fails with a very weird `NullPointerException`:

```
java.lang.ExceptionInInitializerError
    at org.test.tesstates.TestDone.<clinit>(TestDone.java:22)
    at org.test.tesstates.TestState.<clinit>(TestState.java:58)
    at org.test.TestStatesTestCase.testMappingBackAndForth(TestStatesTestCase.java:10)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at [...]
Caused by: java.lang.NullPointerException
    at org.test.tesstates.TestPending.<init>(TestPending.java:18)
    at org.test.tesstates.TestCreated.<init>(TestCreated.java:18)
    at org.test.tesstates.TestCreated.<clinit>(TestCreated.java:5)
    ... 45 more
```

This happens on Java versions <= 1.7. On Java 8, the test succeeds, but we get the following error during instrumentation:

```
Unable to instrument file D:\[...]\cobertura-test\build\instrumented_classes\org\test\tesstates\TestRunning.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:147)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
      [...]
```

Since this is _very_ hard to explain, I put together a small project (with the least possible code) that manages to reproduce the error:
https://dl.dropboxusercontent.com/u/54390273/dev/cobertura-test.zip

Unfortunately, I'm not familiar with maven as we switched to Gradle quite some time ago. So I wrapped the code into a gradle project that uses stevesaliman/gradle-cobertura-plugin to run cobertura. Using the included java example code, it should be easy for you guys to make an existing maven / ant project reproduce the error ;)

**Comment by gluck** [comment]
Encountered this issue as well, and it definitely seems to be a case of [ctor being executed before static init](http://stackoverflow.com/questions/13948170/static-initializer-runs-after-the-constructor-why).
In your case TestCase static init requires TestRunning instance creation (and others) which extends TestCase. In that case the static init can be called after ctor, resulting in your NPE.

**Comment by gluck** [comment]
(my suggestion was to fix the circular static init dependency btw, as it makes the code pretty unreliable, even w/o cobertura in the mix)
