### ISSUE TITLE
using cobertura 2.5.2 not able to publish code coverage results

### ISSUE THREAD

**Issue by saviovettoor** [cobertura/cobertura#178]
java version: jdk1.7.0_17
maven apache-maven-3.0.5
[Cobertura] Publishing Cobertura coverage report...
FATAL: Unable to find coverage results
java.io.IOException: Expecting Ant GLOB pattern, but saw '/var/lib/jenkins/cobertura/coverage.xml'. See http://ant.apache.org/manual/Types/fileset.html for syntax
    at hudson.FilePath.glob(FilePath.java:1624)
    at hudson.FilePath.access$700(FilePath.java:178)
    at hudson.FilePath$30.invoke(FilePath.java:1605)
    at hudson.FilePath$30.invoke(FilePath.java:1602)
    at hudson.FilePath.act(FilePath.java:920)
    at hudson.FilePath.act(FilePath.java:893)
    at hudson.FilePath.list(FilePath.java:1602)
    at hudson.FilePath.list(FilePath.java:1587)
    at hudson.FilePath.list(FilePath.java:1573)
    at hudson.plugins.cobertura.CoberturaPublisher$ParseReportCallable.invoke(CoberturaPublisher.java:530)
    at hudson.plugins.cobertura.CoberturaPublisher$ParseReportCallable.invoke(CoberturaPublisher.java:519)
    at hudson.FilePath.act(FilePath.java:920)
    at hudson.FilePath.act(FilePath.java:893)
    at hudson.plugins.cobertura.CoberturaPublisher.perform(CoberturaPublisher.java:337)
    at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:736)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:685)
    at hudson.model.Run.execute(Run.java:1757)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:234)
[Cobertura] No coverage results were found using the pattern '/var/lib/jenkins/cobertura/coverage.xml' relative to '/var/lib/jenkins/workspace/test'.  Did you enter a pattern relative to the correct directory?  Did you generate the XML report(s) for Cobertura?
Build step 'Publish Cobertura Coverage Report' changed build result to FAILURE
Skipping sonar analysis due to bad build status FAILURE
Finished: FAILURE

pom.xml contains:

```
  <properties>
    <tycho-version>0.15.0</tycho-version>
    <cobertura.version>2.5.2</cobertura.version>    
  </properties>
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>cobertura-maven-plugin</artifactId>
    <version>${cobertura.version}</version>
    <configuration>
        <formats>
            <format>html</format>
            <format>xml</format>
        </formats>
    </configuration>
</plugin>
```

**Comment by Yahsaswi** [comment]
I'm also facing the same issue. I'm unable to give a right path to the cobertura report. Can someone please help me

**Comment by Fireworks643** [comment]
same issue)
