### ISSUE TITLE
NullPointerException at stopping Tomcat with Cobertura 2.0.3

### ISSUE THREAD

**Issue by gwitsch** [cobertura/cobertura#180]
When I stop the tomcat server for cobertura to write the cobertura.ser file, a NullPointerException is thrown.

Instrumentation works fine.
[cobertura-instrument] Information: Cobertura: Saved information on 803 classes.

Start of Tomcat and jUnit Test execution works also fine. Tests pass all with no errors. The jUnit-repors are written successfully. However the coverage data is not written to cobertura.ser.

At stopping the tomcat server, the following exception is thrown:
Exception in thread "Thread-2" java.lang.NullPointerException
    at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:104)
    at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:270)
    at net.sourceforge.cobertura.coveragedata.ProjectData.initialize(ProjectData.java:221)
    at net.sourceforge.cobertura.coveragedata.ProjectData.getGlobalProjectData(ProjectData.java:208)
    at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:248)
    at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:32)
    at java.lang.Thread.run(Thread.java:744)

Tomcat is startet/stopped with cargo.
Any suggestion what goes wrong?

**Comment by dalvizu** [comment]
Looks like someone attempted a work-around if catalina.home is defined:

https://github.com/cobertura/cobertura/blob/dddd1d30d19006c0a0ae0119ac8039557d0e206b/cobertura/src/main/java/net/sourceforge/cobertura/util/ShutdownHooks.java

TouchCollector may need to be added

**Comment by anilverma070** [comment]
I am still seeing this issue with 2.1.1. Cobertura.jar is copied to tomcat's lib as well as WEB-INF/lib of applications.

Exception in thread "Thread-2" java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector$ApplyToClassDataLightClassmapListener
	at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:125)
	at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:110)
	at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272)
	at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector$ApplyToClassDataLightClassmapListener
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1713)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1558)
	... 5 more

**Comment by simplelzl** [comment]
i have the same question with 2.1.1. When i shut down tomcat ,the issue occur.
java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector$ApplyToClassDataLightClassmapListener
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:125) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:110) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33) ~[cobertura-2.1.1.jar:2.1.1]
        at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_45]
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector$ApplyToClassDataLightClassmapListener
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702) ~[na:na]
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547) ~[na:na]
        ... 5 common frames omitted

**Comment by chetanaher** [comment]
Do any one found out solution on this ... I am facing the same

**Comment by simplelzl** [comment]
There are two methods to save coverage.  1.shut down toimcat  2.use coberturaFlush.war, and call the  
saving method.Now the first method is not useful.  I use the second.

**Comment by chetanaher** [comment]
How to use this coberturaFlush.war Do i need to install on server I am using websphere ...
And then what I have to do ?
