### ISSUE TITLE
java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/HasBeenInstrumented

### ISSUE THREAD

**Issue by vallll** [cobertura/cobertura#183]
What could be the possible reason for getting: codenet/sourceforge/cobertura/coveragedata/HasBeenInstrumented.java is missing? 

[cobertura-instrument] Cobertura 2.1.0-SNAPSHOT - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[cobertura-instrument] [main] WARN net.sourceforge.cobertura.instrument.CodeInstrumentationTask$LoggerWrapper - Problems instrumenting archive entry: com/fTEst.class
[cobertura-instrument] java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/HasBeenInstrumented
[cobertura-instrument]  at java.lang.ClassLoader.defineClass1(Native Method)
[cobertura-instrument]  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[cobertura-instrument]  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[cobertura-instrument]  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[cobertura-instrument]  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[cobertura-instrument]  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[cobertura-instrument]  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[cobertura-instrument]  at java.security.AccessController.doPrivileged(Native Method)
[cobertura-instrument]  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[cobertura-instrument]  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[cobertura-instrument]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[cobertura-instrument]  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[cobertura-instrument]  at java.lang.Class.forName0(Native Method)
[cobertura-instrument]  at java.lang.Class.forName(Class.java:270)
[cobertura-instrument]  at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaClassWriter.getCommonSuperClass(CoberturaClassWriter.java:20)
[cobertura-instrument]  at org.objectweb.asm.ClassWriter.a(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.Frame.a(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.Frame.a(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter.visitMaxs(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.ClassReader.b(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.ClassReader.accept(Unknown Source)
[cobertura-instrument]  at org.objectweb.asm.ClassReader.accept(Unknown Source)
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:214)
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToArchive(CodeInstrumentationTask.java:168)
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToArchive(CodeInstrumentationTask.java:267)
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:88)
[cobertura-instrument]  at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74)
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82)
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99)
[cobertura-instrument] Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.HasBeenInstrumented
[cobertura-instrument]  at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[cobertura-instrument]  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[cobertura-instrument]  at java.security.AccessController.doPrivileged(Native Method)
[cobertura-instrument]  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[cobertura-instrument]  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[cobertura-instrument]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[cobertura-instrument]  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[cobertura-instrument]  ... 38 more

**Comment by dennisl** [comment]
Sounds like like a case of different classes loaded by different class loaders.
