### ISSUE TITLE
Failures in tests using jmock?

### ISSUE THREAD

**Issue by jayeye** [cobertura/cobertura#186]
Some of our (otherwise passing) tests fail after being instrumented with cobertura. Example of failure:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.jmock.lib.legacy.ClassImposteriser$3
                        at org.jmock.lib.legacy.ClassImposteriser.createProxyClass(ClassImposteriser.java:98)
                        at org.jmock.lib.legacy.ClassImposteriser.imposterise(ClassImposteriser.java:65)
                        at org.jmock.Mockery.mock(Mockery.java:132)
                        at org.jmock.Mockery.mock(Mockery.java:113)
```

I am using the latest (2.1.0) version available on github. I am running it effectively from the command line (we use our own build tool at Twitter: https://github.com/pantsbuild/pants, for which I have written cobertura support), but I have verified that the right versions of cobertura's dependencies are loaded. Moreover, this is not new, it was also happening in the clone I made of the repo in April 2014 (so, 2.0.3+fixes).

**Comment by sanjaysingh77** [comment]
Were you able to figure this out, I am facing the same problem with our mocks and cobertura, just wondering what did you do to get this working eventually.

Thanks for your help!

**Comment by dennisl** [comment]
Could you please try using the Cobertura 2.1.1 release?
