### ISSUE TITLE
java.lang.NoClassDefFoundError exception at stopping JBOSS with Cobertura 2.1.0

### ISSUE THREAD

**Issue by funkfan82** [cobertura/cobertura#193]
Hi,
I've got similar issue to (#180),  on JBoss (6.1.1) shutdown as well. Any quick suggestion/fix is greatly appreciated as this results in report with 0% coverage. Also this is with yesterdays (Sep 9 2014) 2.1.0-snapshot.

(Thread-113) Exception in thread "Thread-113" java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector$ApplyToClassDataLightClassmapListener
(Thread-113) at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:128)
(Thread-113) at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:112)
(Thread-113) at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272)
(Thread-113) at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33)
(Thread-113) at java.lang.Thread.run(Thread.java:744)
(Thread-113) Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector$ApplyToClassDataLightClassmapListener from Module "deployment.scope.ear:main" from Service Module Loader at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:196)
(Thread-113) at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:444)
(Thread-113) at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:432)
(Thread-113) at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:374)
(Thread-113) at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:119)
(Thread-113) ... 5 more

**Comment by dennisl** [comment]
Does this still happen with the Cobertura 2.1.1 release?

**Comment by emailtomit** [comment]
Dennis, I am still able to see same issue with cobertura 2.1.1

**Comment by emailtomit** [comment]
take a look below error message with JBoss 7.1.3

INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,221 INFO  [org.jboss.as] JBAS015950: JBoss AS 7.1.3.Final "Arges" stopped in 947ms
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,252 ERROR [stderr] Exception in thread "Thread-117" java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector$ApplyToClassDataLightClassmapListener
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,252 ERROR [stderr]   at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:125)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,252 ERROR [stderr]   at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:110)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,252 ERROR [stderr]   at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,253 ERROR [stderr]   at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,253 ERROR [stderr]   at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,253 ERROR [stderr] Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector$ApplyToClassDataLightClassmapListener from [Module "deployment.service.ear:main" from Service Module Loader]
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,253 ERROR [stderr]   at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,253 ERROR [stderr]   at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,253 ERROR [stderr]   at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,253 ERROR [stderr]   at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,254 ERROR [stderr]   at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
INFO   | jvm 1    | 2015/02/27 10:01:52 | 10:01:52,254 ERROR [stderr]   ... 5 more

**Comment by emailtomit** [comment]
I am able to see class and method in Cobertura 2.1.1.. Not sure what causing classNotfound error
