### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.cobertura.coveragedata.TouchCollector

### ISSUE THREAD

**Issue by stefanes** [cobertura/cobertura#230]
With version 2.1.1 I get the following error for some of my projects (not all):
java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.cobertura.coveragedata.TouchCollector

java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.cobertura.coveragedata.TouchCollector
	at com....uiresources.configuration.ResourceImporter.__cobertura_init(ResourceImporter.java)
	at com....uiresources.configuration.ResourceImporter.&lt;clinit&gt;(ResourceImporter.java)
	at com....uiresources.configuration.ResourceImporterTest.testParsing(ResourceImporterTest.java:38)

classpath:
c:\git-repos\1\build\classes\coverage;c:\git-repos\1\build\classes\junit;c:\git-repos\1\build\plugins\cs.ma.download\src\test\resources;c:\git-repos\1\build\plugins\cs.ma.fc.domain\src\test\resources;c:\git-repos\1\build\plugins\cs.ma.fc.localstorage\src\test\resources;c:\git-repos\1\build\plugins\cs.ma3.core.update\src\test\resources;c:\git-repos\1\build\plugins\cs.network\src\test\resources;c:\git-repos\1\build\plugins\cs_ma3_client_sc\src\test\resources;c:\git-repos\1\build\junit-classpath.jar;c:\ivy\cache\org.junit\com.springsource.org.junit\jars\com.springsource.org.junit-4.8.2.jar;c:\ivy\cache\org.easymock\easymock\jars\easymock-3.2.jar;c:\ivy\cache\cglib\cglib-nodep\jars\cglib-nodep-2.2.2.jar;c:\ivy\cache\org.objenesis\objenesis\jars\objenesis-1.3.jar;c:\ivy\cache\net.sourceforge.cobertura\cobertura\jars\cobertura-2.1.1.jar;c:\ivy\cache\org.ow2.asm\asm\jars\asm-5.0.1.jar;c:\ivy\cache\org.ow2.asm\asm-tree\jars\asm-tree-5.0.1.jar;c:\ivy\cache\org.ow2.asm\asm-commons\jars\asm-commons-5.0.1.jar;c:\ivy\cache\org.ow2.asm\asm-util\jars\asm-util-5.0.1.jar;c:\ivy\cache\org.ow2.asm\asm-analysis\jars\asm-analysis-5.0.1.jar;c:\ivy\cache\oro\oro\jars\oro-2.0.8.jar;c:\ivy\cache\jaxen\jaxen\jars\jaxen-1.1.4.jar;c:\ivy\cache\org.apache.ant\ant\jars\ant-1.8.3.jar;c:\ivy\cache\org.apache.ant\ant-launcher\jars\ant-launcher-1.8.3.jar;c:\ivy\cache\org.apache.ant\ant-junit\jars\ant-junit-1.8.3.jar;c:\ivy\cache\org.mortbay.jetty\servlet-api-2.5\jars\servlet-api-2.5-6.1.14.jar;c:\ivy\cache\org.mortbay.jetty\jetty\jars\jetty-6.1.14.jar;c:\ivy\cache\org.mortbay.jetty\jetty-util\jars\jetty-util-6.1.14.jar;c:\ivy\cache\org.slf4j\slf4j-api\jars\slf4j-api-1.7.5.jar;c:\ivy\cache\ch.qos.logback\logback-classic\jars\logback-classic-1.0.13.jar;c:\ivy\cache\ch.qos.logback\logback-core\jars\logback-core-1.0.13.jar;c:\ivy\cache\junit\junit\jars\junit-4.11.jar;c:\ivy\cache\org.hamcrest\hamcrest-core\jars\hamcrest-core-1.3.jar;c:\ivy\cache\org.apache.commons\commons-lang3\jars\commons-lang3-3.3.2.jar;C:\Program Files (x86)\Rational\ClearQuest\cqjni.jar;C:\client-build-tools\ant_1.9.2\lib\ant-launcher.jar;c:\client-build-tools\ant_1.9.2\lib\ant.jar;c:\client-build-tools\ant_1.9.2\lib\ant-junit.jar;c:\client-build-tools\ant_1.9.2\lib\ant-junit4.jar

**Comment by dennisl** [comment]
How do you invoke Cobertura? Via Ant, Maven or command line?
What is your Java version?

**Comment by stefanes** [comment]
Ant, using Java 1.7.0 update 67.

**Comment by mmoayyed** [comment]
Also seeing this. 

Via Travis CI:
- mvn clean cobertura:cobertura coveralls:report -DskipTests=false -Dcobertura.skip=false -Dlog4j.configurationFile=../travis/log4j2.xml

**Comment by mmoayyed** [comment]
This really is making it very difficult to use the plugin, to the point where I may have to remove it :(

**Comment by mmoayyed** [comment]
I am also seeing errors such as:

```
java.lang.NoClassDefFoundError: Could not initialize class org.jasig.cas.util.DefaultUniqueTicketIdGenerator
	at org.jasig.cas.ticket.TicketGrantingTicketImplTests.<init>(TicketGrantingTicketImplTests.java:43)
```

Which makes no sense, because the class can perfectly initialize.

**Comment by nakic** [comment]
I have the same problem on 1 of 2 projects using Java 8, Maven 3, cobertura-maven-plugin 2.7 and cobertura 2.1.1.

Had to revert to 2.6 and use [this workaround](http://www.befreeman.com/2014/09/getting-cobertura-code-coverage-with.html#comment-form) to make it work (without the workaround, cobertura was unable to instrument any classes). Would like to see it fixed in the latest official release, though.

**Comment by feliperoos** [comment]
Got the same thing using Java 8, Maven 3, cobertura-maven-plugin 2.7. Code target is set to 1.7 though. It makes 2.7 version of cobertura-maven-plugin unusable.

**Comment by arellano-gustavo** [comment]
I have fixed my problem just by using the 2.6 version:
           <groupId>org.codehaus.mojo</groupId>
                            <artifactId>cobertura-maven-plugin</artifactId>
                            <version>2.6</version>
                            <configuration>
etc...

**Comment by msiemczyk** [comment]
This is very weird, but I'm also seeing it now. Bunch of dependencies changed so it is hard to say what caused it. But we run mvn site  -Panalysis target and the profile adds reporting plugins including cobertura. 

```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>cobertura-maven-plugin</artifactId>
    <version>${coberturaPlugin.version}</version>
    <configuration>
        <formats>
            <format>html</format>
            <format>xml</format>
        </formats>
    </configuration>
</plugin>
```

We are using 2.7 version with JDK 1.8 and maven 3.5.2, which haven't changed. We have run sometimes into weird dependency issue, where tests don't fail when you run mvn clean install, but running site fails with weird errors, like Guava dependency issues.

**Comment by josemiguel1999** [comment]
Same problem here with version 2.1.1. I instrumented classes and deploy in Glassfish.
.jar is in glassfish/domains/domain1/lib folder.
I call to flush (using war app) and I got this error (obviously the class is there):

  [http-listener-1(2)] ERROR net.sourceforge.cobertura.coveragedata.TouchCollector - Exception when registering class: com/avego/dave/generated/tier1/AttributeNames]]

[2019-03-03T19:41:59.481+0000] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=29 _ThreadName=Thread-9] [timeMillis: 1551642119481] [levelValue: 1000] [[
  java.lang.ClassNotFoundException: com.avego.dave.generated.tier1.AttributeNames
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1783)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1633)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.sourceforge.cobertura.coveragedata.TouchCollector.registerClass(TouchCollector.java:81)
	at com.avego.dave.generated.tier1.AttributeNames.__cobertura_init(AttributeNames.java)
	at com.avego.dave.generated.tier1.AttributeNames.<clinit>(AttributeNames.java)
	at com.avego.dave.etm.lbo.batch.ItsBatchProcessor.__cobertura_classmap_0(ItsBatchProcessor.java)
	at com.avego.dave.etm.lbo.batch.ItsBatchProcessor.__cobertura_classmap(ItsBatchProcessor.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:131)
	at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:110)
	at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.cobertura.webapp.FlushCoberturaServlet.doGet(FlushCoberturaServlet.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.

**Comment by msiemczyk** [comment]
> 
> 
> This is very weird, but I'm also seeing it now. Bunch of dependencies changed so it is hard to say what caused it. But we run mvn site -Panalysis target and the profile adds reporting plugins including cobertura.
> 
> ```
> <plugin>
>     <groupId>org.codehaus.mojo</groupId>
>     <artifactId>cobertura-maven-plugin</artifactId>
>     <version>${coberturaPlugin.version}</version>
>     <configuration>
>         <formats>
>             <format>html</format>
>             <format>xml</format>
>         </formats>
>     </configuration>
> </plugin>
> ```
> 
> We are using 2.7 version with JDK 1.8 and maven 3.5.2, which haven't changed. We have run sometimes into weird dependency issue, where tests don't fail when you run mvn clean install, but running site fails with weird errors, like Guava dependency issues.
> 
> I just run mvn cobertura:cobertura and that works fine on it's own...maybe the maven-site-plugin loads classes differently?

In terms of our issue it turned out that somehow the jar in the local maven repo (on one Jenkins slave) actually had cobertura instrumented classes (and cobertura.ser) in it. In actual maven repo jar was okay and after deleting local copy and redownloading the build is working fine. No idea how that happened.

**Comment by eleumik** [comment]
I fixed it as described by [msiemczyk](https://github.com/msiemczyk) in https://github.com/cobertura/cobertura/issues/230#issuecomment-477699626
