### ISSUE TITLE
ClassNotFoundException for interface with generic

### ISSUE THREAD

**Issue by stefanes** [cobertura/cobertura#231]
With version 2.1.1 I get the following warning for an interface with generic:
public interface ParameterValue<T> {...}

Stacktrace:
[cobertura-instrument] [WARN] Problems instrumenting archive entry: com/.../parameter/ParameterImpl.class
[cobertura-instrument] java.lang.RuntimeException: java.lang.ClassNotFoundException: com.....api.ParameterValue
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaClassWriter.getCommonSuperClass(CoberturaClassWriter.java:35) ~[cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter.visitMaxs(Unknown Source) ~[asm-util-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(Unknown Source) ~[asm-commons-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-tree-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(Unknown Source) ~[asm-util-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(Unknown Source) ~[asm-util-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:214) ~[cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToArchive(CodeInstrumentationTask.java:168) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToArchive(CodeInstrumentationTask.java:267) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:88) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] Caused by: java.lang.ClassNotFoundException: com.....api.ParameterValue
[cobertura-instrument]  at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_67]
[cobertura-instrument]  at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_67]
[cobertura-instrument]  at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_67]
[cobertura-instrument]  at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_67]
[cobertura-instrument]  at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_67]
[cobertura-instrument]  at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_67]
[cobertura-instrument]  at java.lang.Class.forName0(Native Method) ~[na:1.7.0_67]
[cobertura-instrument]  at java.lang.Class.forName(Class.java:270) ~[na:1.7.0_67]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaClassWriter.getCommonSuperClass(CoberturaClassWriter.java:32) ~[cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  ... 22 common frames omitted

Executed using Ant with Java 1.7.0 update 67.

**Comment by stefanes** [comment]
Warning displayed during instrumentation.

**Comment by kadim** [comment]
Same stacktrace encountered in out runs and some files was not instrumented. Not sure why it is just warning...
It feels like classes cannot be loaded as part of instrumentationClasspath because when we added SAME jars as auxClasspath warning is gone.

This is quite strange because according to source instrumentationClasspath is used during Class.forName calls.
