### ISSUE TITLE
OutOfMemoryError When Testing Within Spring Framework

### ISSUE THREAD

**Issue by donnyhallman** [cobertura/cobertura#238]
## Overview ##
Switching from 2.0.3 to 2.1.1 causes the coverage testing to fail due to OutOfMemoryError. I'm running the tests using Ant. Running unit tests are fine, but integration tests where running withing the Spring Framework it quickly runs out of memory after a few test cases in. 

In this application's case, I noticed when running the same integration tests in 2.0.3 that the memory would spike up to ~800MB for various integration tests throughout coverage testing. However, in 2.1.1 after a few tests it started to spike above 2000MB, then essentially run out of Heap Space. I'm not setting the **maxmemory** option, but at the same time, going that high in memory usage seems extreme. This issue has never occurred for this project over the last year when running 2.0.3.

## Environment ##
Java 1.7.65
Spring 3.2.4 RELEASE
Ant: 1.9.2
Commons-IO: 2.4
Commons-Lang3: 3.3.2
* Other dependencies seem to match requirements per Cobertura 2.1.1. POM.

**Comment by donnyhallman** [comment]
I did some more looking and it seems to be related to ASM 5.0.1 if I were to guess. If I **only switch out the cobertura jar** while leaving the other dependencies in place same the same OutOfMemoryError occurs. In other words, dropping back to 2.0.3 jar with 2.1.1 dependencies in use, I get the error.

**Comment by donnyhallman** [comment]
I did some more looking and it seems to be related to ASM 5.0.1 if I were to guess. If I only switch out the cobertura jar while leaving the other dependencies in place same the same OutOfMemoryError occurs. In other words, dropping back to 2.0.3 jar with 2.1.1 dependencies in use, I get the error.

(*I apologize for the "close and reopen". I clicked the wrong button*)

**Comment by donnyhallman** [comment]
Okay so I did some more looking because I didn't want this to hold me back. The issue is actually related to logging and DbUnit. I'm not sure the source of the problem, but with Cobertura 2.1.1 I started getting a stack track at the beginning of running in Ant with the following:

> c:\Program Files\Apache Software Foundation\Tomcat 5.5\logs\api.log (The system cannot find the path specified)
> ....
> at net.sourceforge.cobertura.util.CommandLineBuilder.<clinit>(CommandLineBuilder.java:73)
> at net.sourceforge.cobertura.ant.InstrumentTask.execute(InstrumentTask.java:172)
> ....

This caused an SLF4J problem as far as I can tell, then this caused DbUnit (or someother library) it seems to spew tons debug statements. All this would be happening before it even ran a test as far I can tell. It seems that all of the logging was being written in memory before being written out. I had to do no logs in JUnit and to write to console to see this issue. So it seems in my case 1.5 gigs of output was being placed in memory before tests were even running due to setup for Spring and DbUnit (*without Cobertura 2.1.1 the total peak footprint is perhaps 500MB, where this would bomb a little past 2GB*)

In this case I have a TestExecutionListener that was doing the DbUnit setup so there I programmaticly did the following:

```Java
ch.qos.logback.classic.Logger l = (ch.qos.logback.classic.Logger) org.slf4j.LoggerFactory.getLogger("org.dbunit");
l.setLevel(Level.ERROR);
```

That seemed to work then the whole test suite was running properly. I don't know the internals of Cobertura and DbUnit with also Spring thrown in to understand why all that logging data was being built up and not streamed out, but the fix above worked for me. However, it seems the caused of the DEBUG logging mayhem was caused by the initial exception with logging.
