### ISSUE TITLE
Exception with 2.1.1

### ISSUE THREAD

**Issue by yohkun** [cobertura/cobertura#240]
I got 2 differents types of exception since i pass to 2.1.1 and jdk 8 : 

i2.application.commun.exception.TechnicalException: java.util.ConcurrentModificationException
Caused by: java.util.ConcurrentModificationException

and 

javax.servlet.ServletException: i2.application.commun.exception.TechnicalException: java.lang.ClassCastException: i2.application.agoraa.gestiondemande.valueobject.persistence.impl.VehiculeCABean

Anny idees ?

**Comment by dennisl** [comment]
Without complete stack traces it is very difficult to understand your problem. It would also help is you told us what commands you run to get these errors.

**Comment by yohkun** [comment]
I run junit on instrumented class : 
```
<target name="instrument" depends="compile">
		<cobertura-instrument todir="${cob.instrumented.dir}">
			<classpath refid="classpath.cobertura" />
			<fileset dir="${build.webapp.webinf.dir}/classes">
				<include name="**/*.class" />
			</fileset>
		</cobertura-instrument>
	</target>
<junit dir="${basedir}" printsummary="on" showoutput="true" fork="true" haltonfailure="false" haltonerror="false" >
	<jvmarg value="-XX:-UseSplitVerifier -Xmx2048m -XX:MaxMetaspaceSize=128m" />
	<sysproperty key="log4j.configuration" value="file:${basedir}/test/log4j.properties"/>
	<sysproperty key="net.sourceforge.cobertura.datafile" file="${basedir}/${cob.ser.file}" />
	<classpath refid="cobertura.classpath" />
	<classpath location="${cob.instrumented.dir}" />
```
the exception itself is not really helpfull, maybe it's happends cause i use subclass with hibernate.

like 
```
i2.application.commun.exception.TechnicalException: java.lang.ClassCastException: i2.application.agoraa.gestiondemande.valueobject.persistence.impl.VehiculeCABean
	at i2.application.commun.exception.interceptor.ExceptionInterceptor.afterThrowing(ExceptionInterceptor.java:95)
	at org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor.invokeHandlerMethod(ThrowsAdviceInterceptor.java:144)
	at org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor.invoke(ThrowsAdviceInterceptor.java:129)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy17.update(Unknown Source)
	at i2.application.agoraa.gestiondemande.metier.delegate.GestiondemandeDelegate.update(GestiondemandeDelegate.java:519)
	at i2.application.agoraa.gestiondemande.presentation.action.ca.SupprimerObservationCAAction.doExecuteGestionDemande(SupprimerObservationCAAction.java:72)
	at i2.application.agoraa.commun.presentation.action.AbstractGestionDemandeAction.doExecuteAgoraa(AbstractGestionDemandeAction.java:63)
	at i2.application.agoraa.commun.presentation.action.AbstractAgoraaAction.doExecute(AbstractAgoraaAction.java:45)
	at i2.application.commun.presentation.action.AbstractAction.execute(AbstractAction.java:270)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
	at servletunit.struts.MockStrutsTestCase.actionPerform(MockStrutsTestCase.java:394)
	at i2.application.agoraa.test.ApplicationActionTest.actionPerform(ApplicationActionTest.java:604)
	at i2.application.agoraa.test.gestiondemande.ca.observation.presentation.SupprimerObservationActionTest.testSupprimerMention(SupprimerObservationActionTest.java:55)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.extensions.TestSetup.run(TestSetup.java:27)
Caused by: java.lang.ClassCastException: i2.application.agoraa.gestiondemande.valueobject.persistence.impl.VehiculeCABean
	at org.hibernate.type.EntityType.toLoggableString(EntityType.java:515)
	at org.hibernate.pretty.Printer.toString(Printer.java:76)
	at org.hibernate.pretty.Printer.toString(Printer.java:113)
	at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:120)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1206)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:375)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:137)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:656)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:393)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor.invoke(ThrowsAdviceInterceptor.java:124)
```
or
```
i2.application.commun.exception.TechnicalException: java.util.ConcurrentModificationException
	at i2.application.commun.exception.interceptor.ExceptionInterceptor.afterThrowing(ExceptionInterceptor.java:95)
	at org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor.invokeHandlerMethod(ThrowsAdviceInterceptor.java:144)
	at org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor.invoke(ThrowsAdviceInterceptor.java:129)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy17.update(Unknown Source)
	at i2.application.agoraa.gestiondemande.metier.delegate.GestiondemandeDelegate.update(GestiondemandeDelegate.java:519)
	at i2.application.agoraa.test.gestiondemande.cu_gd_020.metier.SupprimerMentionNotaMetierTest.testSupprimerMentionMetier(SupprimerMentionNotaMetierTest.java:48)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.extensions.TestSetup.run(TestSetup.java:27)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
	at java.util.HashMap$ValueIterator.next(HashMap.java:954)
	at org.hibernate.pretty.Printer.toString(Printer.java:113)
	at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:120)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1206)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:375)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:137)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:656)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:393)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.adapter.ThrowsAdviceInterceptor.invoke(ThrowsAdviceInterceptor.java:124) ```
