### ISSUE TITLE
INVOKESPECIAL/STATIC on interfaces require ASM 5

### ISSUE THREAD

**Issue by cromoteca** [cobertura/cobertura#248]
Using Cobertura 2.1.1 through Maven plugin 2.7, I get this exception:

    Unable to instrument file C:\Pro...\Lambdas.class
    java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
    at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
    at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]

The involved class is very small:

```java
/*
 * Copyright (C) 2015 Luciano Vernaschi <luciano at cromoteca.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.cromoteca.bfts.util;

import java.io.IOException;
import java.util.Comparator;
import java.util.function.Function;
import java.util.stream.Stream;

import static java.util.Comparator.*;
import static java.util.Objects.*;

/**
 * Utilities for lambda expressions
 *
 * @author Luciano Vernaschi <luciano at cromoteca.com>
 */
public class Lambdas {
  private Lambdas() {}

  /**
   * Consumes a stream without having to rethrow IOExceptions as
   * RuntimeExceptions. It uses Stream.forEachOrdered since we need the
   * happens-before contract to be sure that elements that follow an IOException
   * are not processed.
   */
  public static <T> void consumeIO(Stream<T> stream, IOConsumer<T> consumer)
      throws IOException {
    Container<IOException> ioex = new Container<>();

    stream.forEachOrdered(p -> {
      if (ioex.o == null) {
        try {
          consumer.accept(p);
        } catch (IOException ex) {
          ioex.o = ex;
        }
      }
    });

    if (ioex.o != null) {
      throw ioex.o;
    }
  }

  public interface IOConsumer<T> {
    void accept(T t) throws IOException;
  }

  /**
   * Allows to set and retrieve a single object. Used to set and retrieve an
   * object while in a lambda exception (can't set the object directly because
   * it must be effectively final to be used in the lambda body).
   */
  public static class Container<T> {
    public T o;
  }

  /**
   * Used in lambda expressions to sort according to a method of the stream
   * member class. For example, to sort a list of paths by file name, you can
   * write:
   *
   * <pre>paths.sorted(orderBy(Path::getFileName))</pre>
   */
  public static <T, R extends Comparable> Comparator<T> orderBy(Function<T, R> f) {
    return (o1, o2) -> compare(f.apply(o1), f.apply(o2), naturalOrder());
  }
}
```

Test class follows:

```java
package com.cromoteca.bfts.util;

import java.io.IOException;
import java.util.Arrays;
import java.util.stream.Stream;
import org.junit.Test;

import static com.cromoteca.bfts.util.Lambdas.*;
import static org.junit.Assert.*;

public class LambdasTest {
  private static final String PARIS = "Paris";
  private static final String BERLIN = "Berlin";
  private static final String ROMA = "Roma";

  Stream<String> stream
      = Arrays.<String>stream(new String[] { ROMA, BERLIN, PARIS });

  @Test(expected = IOException.class)
  public void testConsumeIOWithoutComparator() throws Exception {
    Lambdas.<String>consumeIO(stream, s -> {
      switch (s) {
        case ROMA:
          break;
        case BERLIN:
          throw new IOException(BERLIN);
        case PARIS:
          fail("IOException should have happened before");
          break;
      }
    });
  }

  @Test(expected = IOException.class)
  public void testConsumeIOWithComparator() throws Exception {
    Lambdas.<String>consumeIO(stream.sorted(String::compareTo), s -> {
      switch (s) {
        case BERLIN:
          break;
        case PARIS:
          throw new IOException(PARIS);
        case ROMA:
          fail("IOException should have happened before");
      }
    });
  }

  @Test
  public void testSort() {
    String[] array = stream.sorted(orderBy(String::length)).toArray(String[]::new);
    assertEquals(ROMA, array[0]);
    assertEquals(PARIS, array[1]);
    assertEquals(BERLIN, array[2]);
  }
}
```
My environment is: jdk1.8.0_40 32 bit on Windows 7 x64, NetBeans 8.

I've just added Cobertura to my project, so the POM configuration is still very basic:

```xml
  <reporting>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
      </plugin>
    </plugins>
  </reporting>
```

**Comment by JWGmeligMeyling** [comment]
Same issue here!

**Comment by vitorscassiano** [comment]
I have the same issue too!

**Comment by porali2000** [comment]
Coverage report spits out below error message  while using cobetura in sonar way

Getting the following ERROR
<code>java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5<code>

Usage:
<code>mvn sonar:sonar<code>

Environment Fields:
Java - 8 | SonarQube 5.1 | Maven 3.3 | 

pom.xml
<code>
 <plugin>  
                <groupId>org.codehaus.mojo</groupId>  
                <artifactId>cobertura-maven-plugin</artifactId>  
                <version>2.7</version>                 
                <configuration>                   
                    <formats>  
                        <format>xml</format> 
                    </formats>                      
                </configuration>  
                
                <dependencies>  
                    <dependency>  
                        <groupId>org.ow2.asm</groupId>  
                        <artifactId>asm</artifactId>  
                        <version>5.0.4</version>  
                    </dependency>  
                </dependencies>  
               
                <executions>                    
                    <execution>  
                        <id>package</id>
                        <phase>package</phase>  
                        <goals>  
                            <goal>cobertura</goal>  
                        </goals>  
                    </execution> 
                    
                </executions> 
                 
            </plugin> 
<code>

Is any solution / fix available for this ?

**Comment by stevendlander** [comment]
I have this same issue with some Java 8 code.

    java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5

**Comment by InfoSec812** [comment]
I too am experiencing this issue when trying to use Cobertura via the Maven plugin on a Vert.x 3.1 project. 

Project code can be found at https://github.com/JUGGL/raffle/tree/cobertura

**Comment by anatolykondratyev** [comment]
Any workaround on this bug? I've also experiencing such behavior.

**Comment by zhoupj** [comment]
I have met this issue with Java 8 code.

**Comment by zhoupj** [comment]
2017-12-25 15:30:17.687||||||ERROR|ContextLoader.initWebApplicationContext||[localhost-startStop-1]-- Context initialization failed
java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.springframework.asm.MethodVisitor.visitMethodInsn(Unknown Source)
	at org.springframework.asm.ClassReader.a(Unknown Source)
	at org.springframework.asm.ClassReader.b(Unknown Source)
	at org.springframework.asm.ClassReader.accept(Unknown Source)
	at org.springframework.asm.ClassReader.accept(Unknown Source)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:64)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:76)
	at org.springframework.context.annotation.ConfigurationClassUtils.checkConfigurationClassCandidate(ConfigurationClassUtils.java:71)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:255)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:225)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:630)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at com.alibaba.citrus.webx.context.WebxComponentsLoader.initWebApplicationContext(WebxComponentsLoader.java:117)
	at com.alibaba.citrus.webx.context.WebxContextLoaderListener.contextInitialized(WebxContextLoaderListener.java:43)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5003)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5517)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1517)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:766)

**Comment by codejayant** [comment]
Is there any resolution or workaround for this issue? I see same issue. using Cobertura version: 2.7

**Comment by perlun** [comment]
Seeing the same thing with Cobertura 2.1.1, using the `gradle-cobertura-plugin-3.0.0.jar` plugin.
