### ISSUE TITLE
cobertura 2.1.1 command line in linux env

### ISSUE THREAD

**Issue by DuXue** [cobertura/cobertura#249]
Hi, did anyone come with this issue, I am trying to execute merge or report in linux environment:
e.g.  bash cobertura-report.sh
error:
Exception in thread "main" java.lang.NoClassDefFoundError: net/sourceforge/cobertura/reporting/ReportMain
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.reporting.ReportMain
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:336)

but the .bat file is working in win enrinment~
I already checked the script class path, seems nothing wrong~

**Comment by dennisl** [comment]
This has been reported by someone before. Apparently the line endings in the .sh files are Windows specific (CRLF). I you change the line endings to be Linux specific (LF) it should work.

**Comment by DuXue** [comment]
@dennisl Thanks, it works! :+1:
