### ISSUE TITLE
java.lang.NullPointerException in server shutdown

### ISSUE THREAD

**Issue by mohanraolv** [cobertura/cobertura#251]
We have IBM WebSphere Application Server 8.0.0.7 installed.

Using maven we have build a sample java application for testing the functional code coverage using cobertura 2.1.1. Application compiled classes were instrumented using the cobertura:instument goal.

The application was deployed on WAS along with providing the cobertura runtime jars. Functional test cases were executed and WAS was shutdown to get the coverage details.

Cobertura.ser file is not created under the working directory of WAS (which will be the profile directory). But it generated the following exception in SystemErr.log.

[5/20/15 15:04:49:465 IST] 0000002b SystemErr     R Exception in thread "Thread-35" java.lang.NullPointerException
[5/20/15 15:04:51:781 IST] 0000002b SystemErr     R 	at org.eclipse.osgi.internal.loader.BundleLoader.findDynamicSource(BundleLoader.java:1068)
[5/20/15 15:04:51:781 IST] 0000002b SystemErr     R 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:474)
[5/20/15 15:04:51:781 IST] 0000002b SystemErr     R 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
[5/20/15 15:04:51:781 IST] 0000002b SystemErr     R 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
[5/20/15 15:04:51:781 IST] 0000002b SystemErr     R 	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
[5/20/15 15:04:51:781 IST] 0000002b SystemErr     R 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:691)
[5/20/15 15:04:51:782 IST] 0000002b SystemErr     R 	at java.lang.ClassLoader.loadClass(ClassLoader.java:678)
[5/20/15 15:04:51:782 IST] 0000002b SystemErr     R 	at com.ibm.ws.bootstrap.ExtClassLoader.loadClass(ExtClassLoader.java:119)
[5/20/15 15:04:51:782 IST] 0000002b SystemErr     R 	at java.lang.ClassLoader.loadClass(ClassLoader.java:661)
[5/20/15 15:04:51:782 IST] 0000002b SystemErr     R 	at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:62)
[5/20/15 15:04:51:782 IST] 0000002b SystemErr     R 	at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:58)
[5/20/15 15:04:51:782 IST] 0000002b SystemErr     R 	at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:566)
[5/20/15 15:04:51:783 IST] 0000002b SystemErr     R 	at java.lang.ClassLoader.loadClass(ClassLoader.java:661)
[5/20/15 15:04:51:783 IST] 0000002b SystemErr     R 	at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:566)
[5/20/15 15:04:51:783 IST] 0000002b SystemErr     R 	at java.lang.ClassLoader.loadClass(ClassLoader.java:661)
[5/20/15 15:04:51:783 IST] 0000002b SystemErr     R 	at net.sourceforge.cobertura.coveragedata.ProjectData.getOrCreateClassData(ProjectData.java:86)
[5/20/15 15:04:51:783 IST] 0000002b SystemErr     R 	at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:109)
[5/20/15 15:04:51:783 IST] 0000002b SystemErr     R 	at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272)
[5/20/15 15:04:51:783 IST] 0000002b SystemErr     R 	at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33)
[5/20/15 15:04:51:784 IST] 0000002b SystemErr     R 	at java.lang.Thread.run(Thread.java:773)

Could anyone please help us in resolving this issue?

Thanks,
Mohan

**Comment by chetanaher** [comment]
Hi Mohanraolv,
  do you find any solution on this
I am facing the same

**Comment by zhuheming222** [comment]
me too
