### ISSUE TITLE
NullPointerException with -parameters compiler option activated

### ISSUE THREAD

**Issue by derjust** [cobertura/cobertura#255]
JDK8 includes a new compiler option `-parameters` to include parameter names for retrieval via the reflection API: http://www.adam-bien.com/roller/abien/entry/named_parameters_in_java_8

Having `.class` files compiled with this flag fail on instrumentation:

```
2015-06-16 10:00:56,555 WARN  | [main] (n.s.c.i.CoberturaInstrumenter:131) | Unable to instrument file /something.class
java.lang.RuntimeException: null
	at org.objectweb.asm.MethodVisitor.visitParameter(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
	at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]
```
This happens with ASM 5.0.1 (maven cobertura plugin) and ASM 5.0.4. 
Subsequently, coverage report is not available.

**Comment by madorb** [comment]
Seeing the same issue.
