### ISSUE TITLE
JavaNCSS error: maven plugin v2.7

### ISSUE THREAD

**Issue by mmoayyed** [cobertura/cobertura#266]
``` java
public static String inflate(final byte[] bytes) {
        try (final ByteArrayInputStream inb = new ByteArrayInputStream(bytes);
             final ByteArrayOutputStream out = new ByteArrayOutputStream();
             final InflaterOutputStream ios = new InflaterOutputStream(out);) {
            IOUtils.copy(inb, ios);
            return new String(out.toByteArray(), UTF8_ENCODING);
        } catch (final Exception e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }
```

causes:

```
[WARN] JavaNCSS got an error while parsing the java file /Users/Misagh/Workspace/GitWorkspace/cas-server/cas-server-core/src/main/java/org/jasig/cas/util/CompressionUtils.java
ParseException in STDIN
Last useful checkpoint: "org.jasig.cas.util.CompressionUtils.inflate(byte[])"
Encountered " "final" "final "" at line 64, column 14.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...
    "false" ...
    "float" ...
    "int" ...
    "long" ...
    "new" ...
    "null" ...
    "short" ...
    "super" ...
    "this" ...
    "true" ...
    "void" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    <STRING_LITERAL> ...
    <IDENTIFIER> ...
    "(" ...
    ")" ...
    "!" ...
    "~" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...


Report time: 510ms

[ERROR] net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " "final" "final "" at line 64, column 14.
```

**Comment by adelinor** [comment]
I am having a similar error with the following line of code:

```java
	private static final String BOM﻿ = "\uFEFF";
```

The error is:

```
[WARN] JavaNCSS got an error while parsing the java file /Users/rodrigues/Documents/workspace/eu.europa.ema.phv.vet.shared/vet-shared-messaging/src/main/java/eu/europa/ema/phv/vet/shared/messaging/all/encoding/MessageEncodingProcessor.java
TokenMgrError in STDIN
Lexical error at line 30, column 40.  Encountered: "\ufeff" (65279), after : ""

Report time: 255ms

[ERROR] net.sourceforge.cobertura.javancss.parser.TokenMgrError: Lexical error at line 30, column 40.  Encountered: "\ufeff" (65279), after : ""
	at net.sourceforge.cobertura.javancss.parser.JavaParserTokenManager.getNextToken(JavaParserTokenManager.java:2057)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_scan_token(JavaParser.java:10375)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_3R_100(JavaParser.java:7053)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_3_12(JavaParser.java:7086)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_2_12(JavaParser.java:6013)
```

**Comment by xylo** [comment]
I get the error on this line:
`return Integer::new;`

Looks like cobertura doesn't like the "::" syntax.
