### ISSUE TITLE
Lambda expression parse error

### ISSUE THREAD

**Issue by jessepl** [cobertura/cobertura#274]
I'am getting error during parsing lambda expression.

```
[ERROR] net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ">" "> "" at line 242, column 48.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...
    "false" ...
    "float" ...
    "int" ...
    "long" ...
    "new" ...
    "null" ...
    "short" ...
    "super" ...
    "this" ...
    "true" ...
    "void" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    <STRING_LITERAL> ...
    <IDENTIFIER> ...
    "(" ...
    "!" ...
    "~" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    
        at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:10490)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:10366)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpression(JavaParser.java:3175)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.MultiplicativeExpression(JavaParser.java:3090)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.AdditiveExpression(JavaParser.java:3085)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ShiftExpression(JavaParser.java:3027)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.RelationalExpression(JavaParser.java:2990)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.InstanceOfExpression(JavaParser.java:2977)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.AssigmentExpression(JavaParser.java:2959)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.EqualityExpression(JavaParser.java:2886)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.AndExpression(JavaParser.java:2860)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ExclusiveOrExpression(JavaParser.java:2843)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.InclusiveOrExpression(JavaParser.java:2826)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalAndExpression(JavaParser.java:2808)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalOrExpression(JavaParser.java:2790)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalExpression(JavaParser.java:2774)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.Expression(JavaParser.java:2718)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ArgumentList(JavaParser.java:3620)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3610)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimarySuffix(JavaParser.java:3511)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimaryExpression(JavaParser.java:3384)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.StatementExpression(JavaParser.java:4070)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3795)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:3984)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.Block(JavaParser.java:3934)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.MethodDeclaration(JavaParser.java:1987)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1039)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:898)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:824)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:728)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:575)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:318)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)
        at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:192)
        at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:268)
        at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:347)
        at net.sourceforge.cobertura.javancss.JavancssFactory.newInstance(JavancssFactory.java:40)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getFunctionMetricsForSingleFile(ComplexityCalculator.java:243)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:273)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:208)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:174)
        at net.sourceforge.cobertura.reporting.html.HTMLReport.generateTableRowForTotal(HTMLReport.java:606)
        at net.sourceforge.cobertura.reporting.html.HTMLReport.generateOverview(HTMLReport.java:290)
        at net.sourceforge.cobertura.reporting.html.HTMLReport.generateOverviews(HTMLReport.java:231)
        at net.sourceforge.cobertura.reporting.html.HTMLReport.<init>(HTMLReport.java:74)
        at net.sourceforge.cobertura.reporting.html.HTMLReportFormatStrategy.save(HTMLReportFormatStrategy.java:18)
        at net.sourceforge.cobertura.reporting.NativeReport.export(NativeReport.java:31)
        at net.sourceforge.cobertura.reporting.CompositeReport.export(CompositeReport.java:19)
        at net.sourceforge.cobertura.reporting.ReportMain.parseArgumentsAndReport(ReportMain.java:91)
        at net.sourceforge.cobertura.reporting.ReportMain.generateReport(ReportMain.java:141)
        at net.sourceforge.cobertura.reporting.ReportMain.main(ReportMain.java:151)
```

**Comment by magmax** [comment]
Me too. Using Java 8 with lambdas.

**Comment by ErikGranse** [comment]
Me as well . . .

**Comment by JAlexoid** [comment]
+1

**Comment by danwms** [comment]
+1

**Comment by komorebicoding** [comment]
+1

**Comment by garagepoort** [comment]
+1

**Comment by svatos-jirka** [comment]
+1 I had migrate to Jacoco

**Comment by Lapeth** [comment]
+1

**Comment by Brennan-VanderLaan** [comment]
+1

**Comment by liyang-bsy** [comment]
+1

**Comment by HolgerPeters** [comment]
This is a reproducing example https://github.com/HolgerPeters/cobertura-reproducing-example. Running with Maven 3.6.0

```
> mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\....\apache-maven-3.6.0\bin\..
Java version: 1.8.0_202, vendor: AdoptOpenJdk, runtime: c:\.....\jdk8u202-b08\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
