### ISSUE TITLE
Exception with Type Annotation on function parameter

### ISSUE THREAD

**Issue by jbf75** [cobertura/cobertura#275]
Hello,
with cobertura 2.1.1 , I have an exception when trying to instrument a class with a type Annotation on a function parameter (with java 8)
Here is a minimal test case: 

import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

@Target(ElementType.TYPE_USE)
@interface TestTypeAnnotation {

}

public class TestCoberturaWithTypeAnnotation {

    void test(@TestTypeAnnotation Object param) {

    }
}
cobertura-instrument.bat TestCoberturaWithTypeAnnotation.class
[WARN] Unable to instrument file C:\cobertura-2.1.1\TestCoberturaWithTypeAnnotation.class
java.lang.RuntimeException: null
        at org.objectweb.asm.MethodVisitor.visitTypeAnnotation(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
        at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
        at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
        at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1
]
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2
.1.1]
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]

Not sure if the issue is on asm 5.0.1 or cobertura 2.1.1 itself

**Comment by mmichaelis** [comment]
Same here for annotations like `org.jetbrains.annotations.NotNull` (`org.jetbrains:annotations`):

```java
AngleUnit(@NotNull String symbol) {
  this.symbol = symbol;
}
```

(here: constructor in an enum).

Also tried to update the asm-dependencies to most recent release 5.1 (cobertura 2.1.1 uses 5.0.1)... but the result was the same. Also tried 6.0_ALPHA.... same effect. Although ASM 5 is reported to support Java 8.

I assume the failure occurs because of a mismatch of `api`:

```java
public AnnotationVisitor visitTypeAnnotation(int typeRef,
        TypePath typePath, String desc, boolean visible) {
    if (api < Opcodes.ASM5) {
        throw new RuntimeException();
    }
    if (mv != null) {
        return mv.visitTypeAnnotation(typeRef, typePath, desc, visible);
    }
    return null;
}
```

I cannot find a bugtracker for ASM... but I assume this is more a bug of ASM rather than Cobertura.
