### ISSUE TITLE
cobertura compilation error on jdk 6

### ISSUE THREAD

**Issue by spacewander** [cobertura/cobertura#283]
Using `Cobertura 2.1.1`.
Run `mvn test` or run `mvn -B clean cobertura:cobertura` with jdk 7, both ok.
Run `mvn -B clean cobertura:cobertura` with jdk 6, then get the following result:

```
[INFO] 
[INFO] <<< cobertura-maven-plugin:2.7:cobertura (default-cli) @ ebs.ecs.proxy <<<
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:cobertura (default-cli) @ ebs.ecs.proxy ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 405 classes.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/DconnectionResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/DeviceResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/DiskInstanceResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/HaVipResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/ImageResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/InstanceTransferOperateService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/InventoryHouyiResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/IpResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/LocationQueryService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/NcQueryService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/OperationResultQueryService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/RcEcsConstant.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/ResourceTransitBackService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/RouterInterfaceResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/SecurityGroupResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/SnapshotResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/VmInstanceResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/VncOperateService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/VncQueryService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/VpcCloudProductService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/VpcPeeringConnectionResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/api/ecs/VpcResourceService.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/ecs/aspect/RouterFailed.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/ecs/aspect/RouterIgnore.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/ecs/router/Router.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/ecs/util/LoggerName.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file com/aliyun/rc/ecs/vm/IVmProxy.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
Report time: 1528ms

[INFO] Cobertura Report generation was successful.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ebs.ecs.services 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ ebs.ecs.services ---
[INFO] Deleting C:\Users\zexuan.lzx\ecs-base-service\ecs.services\target
[INFO] 
[INFO] >>> cobertura-maven-plugin:2.7:cobertura (default-cli) @ ebs.ecs.services >>>
[INFO] 
[INFO] --- maven-staging-plugin:1.1:staging-repository (staging-repository) @ ebs.ecs.services ---
[INFO] No staging repository added
[INFO] 
[INFO] --- maven-build-number-plugin:0.1:create (default) @ ebs.ecs.services ---
[INFO] Storing buildNumber: 12082023 at timestamp: 12082023
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ebs.ecs.services ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 110 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ ebs.ecs.services ---
[INFO] Compiling 1219 source files to C:\Users\zexuan.lzx\ecs-base-service\ecs.services\target\classes
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:instrument (default-cli) @ ebs.ecs.services ---
[INFO] 20:23:43,287 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
20:23:43,288 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
20:23:43,288 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/D:/BackupImportant/mvnlocalrepo/net/sourceforge/cobertura/cobertura/2.1.1/cobertura-2.1.1.jar!/logback.xml]
20:23:43,289 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
20:23:43,289 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/D:/BackupImportant/mvnlocalrepo/com/aliyun/grandcanal/grandcanal-core/2.0.0-1512-SNAPSHOT/grandcanal-core-2.0.0-1512-SNAPSHOT.jar!/logback.xml]
20:23:43,289 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/D:/BackupImportant/mvnlocalrepo/net/sourceforge/cobertura/cobertura/2.1.1/cobertura-2.1.1.jar!/logback.xml]
20:23:43,301 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@676bd8ea - URL [jar:file:/D:/BackupImportant/mvnlocalrepo/net/sourceforge/cobertura/cobertura/2.1.1/cobertura-2.1.1.jar!/logback.xml] is not of type file
20:23:43,406 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:23:43,418 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:23:43,425 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
20:23:43,443 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:23:43,474 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sourceforge.cobertura] to INFO
20:23:43,474 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
20:23:43,474 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
20:23:43,475 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:23:43,476 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@596e1fb1 - Registering current configuration as safe fallback point

Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Saved information on 1252 classes.
[INFO] Cobertura: Saved information on 1252 classes.

[ERROR] SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/BackupImportant/mvnlocalrepo/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/BackupImportant/mvnlocalrepo/org/slf4j/slf4j-log4j12/1.6.2/slf4j-log4j12-1.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ebs.ecs.services ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 60 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ ebs.ecs.services ---
[INFO] Compiling 304 source files to C:\Users\zexuan.lzx\ecs-base-service\ecs.services\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
编译器 (1.6.0_45) 中出现异常。 如果在 Bug Parade 中没有找到该错误，请在 Java Developer Connection (http://java.sun.com/webapps/bugreport)  对该错误进行归档。 请在报告中附上您的程序和以下诊断信息。谢谢您的合作。
java.lang.NullPointerException
	at com.sun.tools.javac.code.Symbol$MethodSymbol.params(Symbol.java:1196)
	at com.sun.tools.javac.jvm.ClassReader.attachParameterAnnotations(ClassReader.java:1111)
	at com.sun.tools.javac.jvm.ClassReader.readMemberAttr(ClassReader.java:871)
	at com.sun.tools.javac.jvm.ClassReader.readMemberAttrs(ClassReader.java:1027)
	at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:1490)
	at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:1586)
	at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:1658)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:1845)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:1777)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:698)
	at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:179)
	at com.sun.tools.javac.comp.Resolve.findMemberType(Resolve.java:894)
	at com.sun.tools.javac.comp.Resolve.findIdentInType(Resolve.java:1064)
	at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:1943)
	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:1835)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1522)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:390)
	at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:681)
	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:545)
	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:495)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:387)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:399)
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:512)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:446)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:387)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:819)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:464)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:442)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:822)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)
	at com.sun.tools.javac.main.Main.compile(Main.java:353)
	at com.sun.tools.javac.main.Main.compile(Main.java:279)
	at com.sun.tools.javac.main.Main.compile(Main.java:270)
	at com.sun.tools.javac.Main.compile(Main.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:551)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:526)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:167)
	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:678)
	at org.apache.maven.plugin.TestCompilerMojo.execute(TestCompilerMojo.java:161)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ebs.all ........................................... SUCCESS [0.843s]
[INFO] ebs.commons.test .................................. SUCCESS [2.102s]
[INFO] ebs.commons.common ................................ SUCCESS [6.688s]
[INFO] ebs.ecs.proxy ..................................... SUCCESS [36.144s]
[INFO] ebs.ecs.services .................................. FAILURE [25.261s]
[INFO] ebs.bundle.war .................................... SKIPPED
[INFO] test.ebs.ecs.services ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

From where can I get more debug information?

**Comment by Tanemahuta** [comment]
http://bugs.java.com/view_bug.do?bug_id=6889255

**Comment by jmrozanec** [comment]
@spacewander thank you for reporting this!
