### ISSUE TITLE
cobertura parse error

### ISSUE THREAD

**Issue by amitmaheshwari** [cobertura/cobertura#291]
I am running cobertura-maven v2.7 and getting following error in my project. I'll appreciate your timely help in resolving this issue.:

[INFO] Cobertura: Loaded information on 469 classes.
[WARN] JavaNCSS got an error while parsing the java file C:\club\small-business\small-business\sb-common-service\src\main\java\com\club\smallbusiness\service\SBDrawCreditReportServiceImpl.java
ParseException in STDIN
Last useful checkpoint: "com.club.smallbusiness.service.SBDrawCreditReportServiceImpl.getDrawCSIIds(Long)"
Encountered " ":" ": "" at line 251, column 64.
Was expecting one of:
    "instanceof" ...
    ")" ...
    "," ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    "+=" ...
    "-=" ...
    "*=" ...
    "/=" ...
    "&=" ...
    "|=" ...
    "^=" ...
    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...
    "<" ...
    

Report time: 2266ms

[ERROR] net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ":" ": "" at line 251, column 64.
Was expecting one of:
    "instanceof" ...
    ")" ...
    "," ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    "+=" ...
    "-=" ...
    "*=" ...
    "/=" ...
    "&=" ...
    "|=" ...
    "^=" ...
    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...
    "<" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:10490)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:10366)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3616)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimarySuffix(JavaParser.java:3511)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimaryExpression(JavaParser.java:3384)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PostfixExpression(JavaParser.java:3330)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpressionNotPlusMinus(JavaParser.java:3237)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpression(JavaParser.java:3171)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.MultiplicativeExpression(JavaParser.java:3090)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AdditiveExpression(JavaParser.java:3061)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ShiftExpression(JavaParser.java:3027)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.RelationalExpression(JavaParser.java:2990)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.InstanceOfExpression(JavaParser.java:2977)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AssigmentExpression(JavaParser.java:2959)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.EqualityExpression(JavaParser.java:2886)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AndExpression(JavaParser.java:2860)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ExclusiveOrExpression(JavaParser.java:2843)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.InclusiveOrExpression(JavaParser.java:2826)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalAndExpression(JavaParser.java:2808)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalOrExpression(JavaParser.java:2790)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalExpression(JavaParser.java:2774)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Expression(JavaParser.java:2718)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ArgumentList(JavaParser.java:3620)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3610)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimarySuffix(JavaParser.java:3511)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimaryExpression(JavaParser.java:3384)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.PostfixExpression(JavaParser.java:3330)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpressionNotPlusMinus(JavaParser.java:3237)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpression(JavaParser.java:3171)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.MultiplicativeExpression(JavaParser.java:3090)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AdditiveExpression(JavaParser.java:3061)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ShiftExpression(JavaParser.java:3027)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.RelationalExpression(JavaParser.java:2990)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.InstanceOfExpression(JavaParser.java:2977)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AssigmentExpression(JavaParser.java:2959)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.EqualityExpression(JavaParser.java:2886)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AndExpression(JavaParser.java:2860)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ExclusiveOrExpression(JavaParser.java:2843)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.InclusiveOrExpression(JavaParser.java:2826)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalAndExpression(JavaParser.java:2808)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalOrExpression(JavaParser.java:2790)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalExpression(JavaParser.java:2774)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Expression(JavaParser.java:2718)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.VariableInitializer(JavaParser.java:1744)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.VariableDeclarator(JavaParser.java:1672)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.LocalVariableDeclaration(JavaParser.java:4019)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:3941)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Block(JavaParser.java:3934)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.MethodDeclaration(JavaParser.java:1987)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1039)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:898)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:824)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:728)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:575)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:318)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)
	at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:192)
	at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:268)
	at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:347)
	at net.sourceforge.cobertura.javancss.JavancssFactory.newInstance(JavancssFactory.java:40)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getFunctionMetricsForSingleFile(ComplexityCalculator.java:243)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:273)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:208)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:174)
	at net.sourceforge.cobertura.reporting.xml.XMLReport.<init>(XMLReport.java:70)
	at net.sourceforge.cobertura.reporting.xml.XMLReportFormatStrategy.save(XMLReportFormatStrategy.java:18)
	at net.sourceforge.cobertura.reporting.NativeReport.export(NativeReport.java:31)
	at net.sourceforge.cobertura.reporting.CompositeReport.export(CompositeReport.java:19)
	at net.sourceforge.cobertura.reporting.ReportMain.parseArgumentsAndReport(ReportMain.java:91)
	at net.sourceforge.cobertura.reporting.ReportMain.generateReport(ReportMain.java:141)
	at net.sourceforge.cobertura.reporting.ReportMain.main(ReportMain.java:151)

[INFO] Cobertura Report generation was successful.
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 469 classes.
[WARN] JavaNCSS got an error while parsing the java file C:\club\small-business\small-business\sb-common-service\src\main\java\com\club\sb\service\SBDrawCreditReportServiceImpl.java
ParseException in STDIN
Last useful checkpoint: "com.club.sb.service.SBDrawCreditReportServiceImpl.getDrawCSIIds(Long)"
Encountered " ":" ": "" at line 251, column 64.
Was expecting one of:
    "instanceof" ...
    ")" ...
    "," ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    "+=" ...
    "-=" ...
    "*=" ...
    "/=" ...
    "&=" ...
    "|=" ...
    "^=" ...
    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...
    "<" ...
    

[INFO] Data file does not contain instrumentation information for the file com/club/common/alibaba/eventexecutor/AlibabaRequestExecutor.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.

**Comment by amitmaheshwari** [comment]
Here are logs before test execution:

[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file

[ERROR] Jan 20, 2016 11:09:44 AM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler saveCoverageData
INFO: Cobertura: Saved information on 469 classes.

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.

**Comment by Koziolek** [comment]
Same problem. Cobertura parser cannot into method references :(

**Comment by jmrozanec** [comment]
@amitmaheshwari thank you for reporting this!
