### ISSUE TITLE
Could not initialize class ...

### ISSUE THREAD

**Issue by headiron** [cobertura/cobertura#293]
Hi All.

I am using cobertura at Maven and whole tests are failed with Could not initialize class ...
When I check the surefire report directory I see the below errors.

  <testcase classname="com.XXXX.DateTest" name="test[0]" time="0.013">
    <error message="org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;" type="java.lang.NoSuchMethodError">java.lang.NoSuchMethodError: org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at net.sourceforge.cobertura.coveragedata.TouchCollector.&lt;clinit&gt;(TouchCollector.java:40)
	at com.XXX.__cobertura_init(ToolShed.java)

I'm not sure, but it looks like version conflict between libraries. But I can't figure out which library has a problem.
http://stackoverflow.com/questions/5477942/slf4j-version-conflict-while-building-through-the-maven

FYI, actual testcases are run successfully. Only cobertura failed for whole testcases

**Comment by jmrozanec** [comment]
@headiron thank you for reporting this!
