### ISSUE TITLE
Cobertura 2.1.1 java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5

### ISSUE THREAD

**Issue by bartlomiej-gora** [cobertura/cobertura#303]
Hi.
I'm using ant, and Jenkins to deploy our system.

Durring build I'm getting this in the logs:

`[cobertura-instrument] [WARN] Unable to instrument file...
[cobertura-instrument] java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
[cobertura-instrument] 	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument] 	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument] 	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument] 	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument] 	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1] `
next line:
`[cobertura-instrument] java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5`

And couple lines down:
`cobertura-instrument] java.lang.RuntimeException: java.lang.ClassNotFoundException:`

Is there any way to fix this?
Most of the classes that are mention in log have 100% coverage (0/0).
We are using java 8, lamda, and groovy for tests.
And For some tests the reports looks fine, and some other not.

Thank you.

**Comment by mjhaller** [comment]
See https://github.com/cobertura/cobertura/pull/299 which I think fixes this issue.

I'd be interested in knowing if there is any plan for a new release which would contain this.

**Comment by Saiftari** [comment]
@mjhaller : Do you know the fix is already released? which cobertura version?

**Comment by azige** [comment]
I'm new to it and was trapped in the same problem. Hope the fix could be released soon.

**Comment by jpopadak** [comment]
Getting the same issue here with 2.1.1 in an all Java project.
