### ISSUE TITLE
No coverage report  when tomcat shut down,ApplyToClassDataLightClassmapListener not found

### ISSUE THREAD

**Issue by simplelzl** [cobertura/cobertura#306]
**  Using the commandLine, when i shut down tomcat ,the following questions produce,the coverage is zero.**

`  java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector$ApplyToClassDataLightClassmapListener
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:125) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:110) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272) ~[cobertura-2.1.1.jar:2.1.1]
        at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33) ~[cobertura-2.1.1.jar:2.1.1]
        at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_45]
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector$ApplyToClassDataLightClassmapListener
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702) ~[na:na]
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547) ~[na:na]`
  
**   I have move the cobertura.jar to tomcat's WEB-INF/lib and tomcat7/lib.  But this issue still occur.**
 
 `version 1.9.4.1:
	* Fix a problem that occurs in Tomcat.   When TouchCollector 
	  initializes, it calls ProjectData.initialize() which (with 
	  Tomcat only) eventually calls TouchCollector.   However, 
	  TouchCollector's static members have not been initialized.   
	  Added a test that highlights this problem.   (Thanks to Jack Cobb
	  for suggesting the fix).
	* Runs on Java 5.  (Fix for Bug 2962599).`
   I think that this issue may similar to  the question above.

**Comment by jmrozanec** [comment]
@simplelzl thank you for reporting this!
