### ISSUE TITLE
Issue running cobertura and PowerMock

### ISSUE THREAD

**Issue by boardbloke** [cobertura/cobertura#308]
I get the following stack dump when using power mock to mock a static method.  I have attached a gradle build that reproduces the problem...

java.lang.NoSuchMethodException:`
[gradleCobertura.zip](https://github.com/cobertura/cobertura/files/270291/gradleCobertura.zip)
 spockpoc.simple.JavaClassCallingGroovyStatic.__
cobertura_classmap(net.sourceforge.cobertura.coveragedata.LightClassmapListener)

        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToS
ingleClassOnProjectData(TouchCollector.java:127)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnP
rojectData(TouchCollector.java:110)
        at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectD
ata(ProjectData.java:272)
        at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:3
3)
        at java.lang.Thread.run(Thread.java:745)
[ERROR] Cannot apply touches
java.lang.NoSuchMethodException: spockpoc.simple.GroovyClassContainingStatic.__c
obertura_classmap(net.sourceforge.cobertura.coveragedata.LightClassmapListener)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToS
ingleClassOnProjectData(TouchCollector.java:127)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnP
rojectData(TouchCollector.java:110)
        at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectD
ata(ProjectData.java:272)
        at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:3
3)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by jmrozanec** [comment]
@boardbloke thank you for reporting this!
