### ISSUE TITLE
java.lang.ExceptionInInitializerError from the constructor of an inner class

### ISSUE THREAD

**Issue by jose** [cobertura/cobertura#321]
Hi,

I found a very weird example in which Cobertura instrumentation code is not properly initialized, and therefore it throws a `java.lang.ExceptionInInitializerError` exception.

Suppose that I've the following class:
```
public abstract class Foo {

  public static final ExtendsFoo extendsFoo = new ExtendsFoo();

  protected Foo() {
    super();
  }

  public static class ExtendsFoo extends Foo {
    public ExtendsFoo() {
      super();
    }
  }
}
```

and I would like to get the coverage of the following test case:
```
import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class TestFoo {

  @Test
  public void test() {
    Foo.ExtendsFoo other_foo = new Foo.ExtendsFoo();
    assertNotNull(other_foo);
  }
}
```

steps to instrument the class under test:
```
$ ls
./  ../  cobertura-2.1.1/  Foo.java  TestFoo.java

$ javac -cp .: Foo.java
$ javac -cp .:cobertura-2.1.1/lib/junit-4.11.jar TestFoo.java

$ sh cobertura-2.1.1/cobertura-instrument.sh Foo.class                           
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Saved information on 1 classes.
[INFO] Cobertura: Saved information on 1 classes.

$ sh cobertura-2.1.1/cobertura-instrument.sh Foo\$ExtendsFoo.class 
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 1 classes.
[INFO] Cobertura: Saved information on 2 classes.
[INFO] Cobertura: Saved information on 2 classes.
```

and then, when I run the test case (using for example JUnit command line) on the instrumented code:
`$ java -cp .:cobertura-2.1.1/lib/junit-4.11.jar:cobertura-2.1.1/lib/hamcrest-core-1.3.jar:cobertura-2.1.1/cobertura-2.1.1.jar:cobertura-2.1.1/lib/slf4j-api-1.7.5.jar org.junit.runner.JUnitCore TestFoo`

I get the following error:
```
JUnit version 4.11
.SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
E
Time: 0.077
There was 1 failure:
1) test(TestFoo)
java.lang.ExceptionInInitializerError
	at TestFoo.test(TestFoo.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	...
Caused by: java.lang.NullPointerException
	at Foo$ExtendsFoo.<init>(Foo.java:11)
	at Foo.<clinit>(Foo.java:3)
	... 32 more

FAILURES!!!
Tests run: 1,  Failures: 1

Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class Foo
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:123)
	at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:110)
	at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272)
	at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33)
	at java.lang.Thread.run(Thread.java:745)
```

looking at the source-code and bytecode of the class under test the reason of this `NullPointerException` is that the constructor of `Foo$ExtendsFoo` is called before `Foo$ExtendsFoo.__cobertura_counters` is initialized by it's static constructor. A possible workaround is to add `__cobertura_init();` to **all** constructors, and not just the static ones.

btw, my system is
- Debian GNU/Linux 8 64-Bits
- Java OpenJDK 1.8.0_91 64-Bit
- Cobertura 2.1.1

**Comment by jmrozanec** [comment]
@jose the project is still alive 😄  Thank you for reporting this. You are welcome to propose solutions and to contribute to the project!
