### ISSUE TITLE
Not able to instrument a class which is importing another class that implements "Serializable"

### ISSUE THREAD

**Issue by hareeshpv** [cobertura/cobertura#331]
Hi,

Cobertura 2.1.1 is not able to implement a class(UserConsentServlet) that is importing a Serializable class(SessionInfo which is implementing Serializable interface). Dont know whether this is only for Serializable or all the interfaces
But the imported class(SessionInfo class) was instrumented.

I dont have permission to show case my code. I am a QA guy who should check coverage of our company live projects. Please help me ASAP

**log :** 
_[WARN] Unable to instrument file /usr/local/tomcat/webapps/jauthws/WEB-INF/classes/com/juno/WebServer/**UserConsentServlet**.class
java.lang.RuntimeException: java.lang.ClassNotFoundException: **com.juno.cachemanager.SessionInfo**
Caused by: java.lang.ClassNotFoundException: com.juno.cachemanager.SessionInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_45-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45-internal]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45-internal]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_45-internal]
	at net.sourceforge.cobertura.instrument.CoberturaClassWriter.getCommonSuperClass(CoberturaClassWriter.java:45) ~[cobertura-2.1.1.jar:2.1.1]_

**Comment by jmrozanec** [comment]
@hareeshpv thank you for reporting this. Even if you cannot showcase your code, could you provide some test reproducing the issue? Something short - so that we can debug and have an acceptance criteria about when is fixed. Thanks!
