### ISSUE TITLE
Host http://cobertura.sourceforge.net/ is always times out

### ISSUE THREAD

**Issue by ipodib** [cobertura/cobertura#369]
Currently when running cobertura plugin it fails with operation timeout exception. It appears that host http://cobertura.sourceforge.net/ is root of cause of that since it can't be reached.
```
rg.dom4j.DocumentException: Operation timed out (Connection timed out) Nested exception: Operation timed out (Connection timed out)
	at org.dom4j.io.SAXReader.read(SAXReader.java:484)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:132)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:302)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:244)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:175)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:154)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:126)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:132)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:107)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2719)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by neilsh** [comment]
related to: https://github.com/cobertura/cobertura/issues/366
