### ISSUE TITLE
Try with resources - net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ")" ") ""

### ISSUE THREAD

**Issue by msiemczyk** [cobertura/cobertura#379]
Try resource block can have semicolon at the end of variable definition and not have another variable. Java compiler will allow one additional semicolon, but Cobertura throws exception because that code was broken when update for Java 7 was made.

![image](https://user-images.githubusercontent.com/5693250/42790748-aa11078a-893a-11e8-9092-44e70617c9f7.png)

There is also associated ERROR logged with it.

> [ERROR] net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ")" ") "" at line 149, column 51.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:11168)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:11041)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Type(JavaParser.java:2533)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.LocalVariableDeclaration(JavaParser.java:4129)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TryWithResources(JavaParser.java:4833)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TryBlock(JavaParser.java:4794)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TryStatement(JavaParser.java:4737)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3943)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:4094)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Block(JavaParser.java:4044)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.MethodDeclaration(JavaParser.java:1995)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1078)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:938)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:863)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:765)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:611)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:354)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)
	at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:216)
	at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:299)
	at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:474)
	at net.sourceforge.cobertura.javancss.JavancssFactory.newInstance(JavancssFactory.java:41)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getFunctionMetricsForSingleFile(ComplexityCalculator.java:243)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:273)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:208)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:174)
	at net.sourceforge.cobertura.reporting.xml.XMLReport.<init>(XMLReport.java:70)
	at net.sourceforge.cobertura.reporting.xml.XMLReportFormatStrategy.save(XMLReportFormatStrategy.java:20)
	at net.sourceforge.cobertura.reporting.NativeReport.export(NativeReport.java:31)
	at net.sourceforge.cobertura.reporting.CompositeReport.export(CompositeReport.java:19)
	at net.sourceforge.cobertura.reporting.ReportMain.parseArgumentsAndReport(ReportMain.java:95)
	at net.sourceforge.cobertura.reporting.ReportMain.generateReport(ReportMain.java:145)
	at net.sourceforge.cobertura.reporting.ReportMain.main(ReportMain.java:155)
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ")" ") "" at line 352, column 116.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:11168)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:11041)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Type(JavaParser.java:2533)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.LocalVariableDeclaration(JavaParser.java:4129)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TryWithResources(JavaParser.java:4833)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TryBlock(JavaParser.java:4794)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TryStatement(JavaParser.java:4737)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3943)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:4094)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Block(JavaParser.java:4044)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3874)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ForStatement(JavaParser.java:4577)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3924)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:4094)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Block(JavaParser.java:4044)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.MethodDeclaration(JavaParser.java:1995)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1078)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:938)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:863)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.NestedClassDeclaration(JavaParser.java:1047)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1068)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:938)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:863)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:765)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:611)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:354)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)
	at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:216)
	at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:299)
	at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:474)
	at net.sourceforge.cobertura.javancss.JavancssFactory.newInstance(JavancssFactory.java:41)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getFunctionMetricsForSingleFile(ComplexityCalculator.java:243)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:273)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:208)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:174)
	at net.sourceforge.cobertura.reporting.xml.XMLReport.<init>(XMLReport.java:70)
	at net.sourceforge.cobertura.reporting.xml.XMLReportFormatStrategy.save(XMLReportFormatStrategy.java:20)
	at net.sourceforge.cobertura.reporting.NativeReport.export(NativeReport.java:31)
	at net.sourceforge.cobertura.reporting.CompositeReport.export(CompositeReport.java:19)
	at net.sourceforge.cobertura.reporting.ReportMain.parseArgumentsAndReport(ReportMain.java:95)
	at net.sourceforge.cobertura.reporting.ReportMain.generateReport(ReportMain.java:145)
	at net.sourceforge.cobertura.reporting.ReportMain.main(ReportMain.java:155)

**Comment by msiemczyk** [comment]
In Java1.1.jj the problem is with TryWithResource, which used to allow optional semicolon.

```
void TryWithResources() :
{}
{
//  LocalVariableDeclaration() [ ";" ]
  LocalVariableDeclaration() ( ";" LocalVariableDeclaration() )*
}
```

**Comment by msiemczyk** [comment]
I triggered the Travis build on my branch and it looks like it's fine:

https://travis-ci.org/msiemczyk/cobertura/builds/405387073
