### ISSUE TITLE
Java 11 Compatibility check: cobertura

### ISSUE THREAD

**Issue by KryniuPL** [cobertura/cobertura#381]
Hi,
We are reaching out to you to check Java 11 compatibility of the library cobertura.

Could you help us by answering the following questions:

1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

Appreciate your response by 19.08.2018.

Thanks,
Krzysztof Dragan,
PTC Inc. Contractor

**Comment by skozlov** [comment]
It seems like Cobertura doesn't support Java 11, because it uses [ASM 5.0.1](https://github.com/cobertura/cobertura/blob/master/pom.xml#L118), which does not support Java 11 bytecode (see https://asm.ow2.io/versions.html).

For example, when I try measuring test coverage using [gradle-cobertura-plugin](https://github.com/stevesaliman/gradle-cobertura-plugin), I get

```
> Task :api:instrument
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Unable to instrument file <module path>/build/instrumented_classes/<package>/App.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:155)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90)
        at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74)
        at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82)
```
