### ISSUE TITLE
NullPointerException in TouchCollector from Cobertura version 2.1.1

### ISSUE THREAD

**Issue by preetirk317** [cobertura/cobertura#401]
Hi, We are facing NPE while running the unit tests. Please find full stack trace as below,

```
Unable to load cache item

java.lang.IllegalStateException: Unable to load cache item
at org.easymock.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
at org.easymock.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
at org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
at org.easymock.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
at org.easymock.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:173)
at org.easymock.internal.MocksControl.createMock(MocksControl.java:116)
at org.easymock.internal.MocksControl.createMock(MocksControl.java:95)
at org.powermock.api.easymock.PowerMock.doCreateMock(PowerMock.java:2023)
at org.powermock.api.easymock.PowerMock.doMock(PowerMock.java:1970)
at org.powermock.api.easymock.PowerMock.mockStatic(PowerMock.java:259)
at cbss.unit.com.ibm.wdp.bss.prov.provisioning.CorePostProcessorTest.mockSeatUtil(CorePostProcessorTest.java:461)
at cbss.unit.com.ibm.wdp.bss.prov.provisioning.CorePostProcessorTest.postProcessEntitleSubscriberEventTest(CorePostProcessorTest.java:43)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
Caused by: java.lang.ExceptionInInitializerError
at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:142)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:121)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:332)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305)
at net.sourceforge.cobertura.coveragedata.TouchCollector.<clinit>(TouchCollector.java:40)
at com.ibm.wdp.bss.seat.util.SeatUtil.__cobertura_init(SeatUtil.java)
at com.ibm.wdp.bss.seat.util.SeatUtil.<clinit>(SeatUtil.java)
at java.lang.Class.forNameImpl(Native Method)
at java.lang.Class.forName(Class.java:348)
at org.easymock.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:467)
at org.easymock.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
at org.easymock.cglib.proxy.Enhancer.generate(Enhancer.java:492)
at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
at org.easymock.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
at java.util.concurrent.FutureTask.run(FutureTask.java:277)
at org.easymock.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
Caused by: java.lang.NullPointerException
at net.sourceforge.cobertura.coveragedata.TouchCollector.registerClass(TouchCollector.java:49)
at net.sourceforge.cobertura.coveragedata.TouchCollector.registerClass(TouchCollector.java:85)
at org.slf4j.impl.StaticLoggerBinder.__cobertura_init(StaticLoggerBinder.java)
at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java)
```

We tried to change the slf4j jar version from 1.6 to 1.7.10, still hitting the same issue. 

Can someone please suggest if any solution already available? 
Also, if this issue is already reported and any new release is available then could you please point it out. 

Thank you.

**Comment by raghavgautam** [comment]
This is likely a duplicate bug. I think this patch will fix the issue:
https://github.com/cobertura/cobertura/pull/325
