### ISSUE TITLE
ClassNotFoundException instrumenting code

### ISSUE THREAD

**Issue by stevesaliman** [cobertura/cobertura#49]
I'm sorry for the duplicate, but I couldn't find a way to reopen the existing issue.

I've done a pull and build with the latest cobertura code, but I still get a lot of ClassNotFoundExceptions from org.objectweb.asm.ClassWriter.getCommonSuperClass in both java 6 and java 7 during instrumentation. Is there something different I need to do to get the auxiliary classpath to work? Is there code that hasn't been merged yet? Is there something else I need to look at?

**Comment by trothwell** [comment]
I just got bit by this bug. Looks like 2.0.4 release got renamed for 2.1.0.

As my team has a strict bar for code coverage, we may need to migrate to JaCoCo if a release doesn't come out quickly.

**Comment by dennisl** [comment]
We are currently working on getting 2.1.0 released.

**Comment by dennisl** [comment]
Cobertura 2.1.1 has been relesed. Please give it a try.

**Comment by jpschewe** [comment]
Works for me.

**Comment by hejack** [comment]
my project is error for Cobertura 2.1.1.
can you help me?

**Comment by celdridge91190** [comment]
I am having a simliar issue with cobertura 2.1.1. Below is my instrument classes target. ${global_target-dir} is the directory where all of the dependency jars are located. I've tried going through the different topics on this and cannot find a solution. 
    <target name="cobertura:instrument-classes" depends="-project:initialize, -cobertura:initialize, -cobertura:taskdefs" extensionOf="process-classes" if="${coverage_enabled}">
        <cobertura-instrument datafile="${cobertura_coverage-file}" todir="${coverage_instrumented-classes-dir}">
            <fileset refid="cobertura_instrumented-classes" />
    		<auxClassPath>
    			<path id="cobertura-auxpath">
    				<fileset dir="${global_target-dir}/lib/runtime/jar">
    					<include name="*/jar"/>
    				</fileset>
    			</path>
    			<pathelement location="${global_target-dir}/lib/runtime/jar/sec.jar"/>
			</auxClassPath>
        </cobertura-instrument>
    </target>

**Comment by celdridge91190** [comment]
For some reason my target was removed from that comment. Here it is below:
    <target name="cobertura:instrument-classes" depends="-project:initialize, -cobertura:initialize, -cobertura:taskdefs" extensionOf="process-classes" if="${coverage_enabled}">
        <cobertura-instrument datafile="${cobertura_coverage-file}" todir="${coverage_instrumented-classes-dir}">
            <fileset refid="cobertura_instrumented-classes" />
    		<auxClassPath>
    			<path id="cobertura-auxpath">
    				<fileset dir="${global_target-dir}/lib/runtime/jar">
    					<include name="*/jar"/>
    				</fileset>
    			</path>
    			<pathelement location="${global_target-dir}/lib/runtime/jar/sec.jar"/>
			</auxClassPath>
        </cobertura-instrument>
    </target>

**Comment by celdridge91190** [comment]
Not sure why my formatting went all goofy, sorry about that, not sure how to fix that

**Comment by justinwm** [comment]
Have the same problem on version 2.1.1 when instrumenting classes

`[WARN] Unable to instrument file Lang_38_buggy/target/classes/org/apache/commons/lang3/time/FastDateFormat.class
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.commons.lang3.time.FastDateFormat$Pair`

However, FastDataFormat$Pair is a inner class defined in FastDateFormat, and actually they can all be found on the same location:


![h_qbv p _zviu7o1 _ 8m](https://cloud.githubusercontent.com/assets/2504533/22281893/4b46a8b8-e314-11e6-97b8-3fa163cae51a.png)

Is anyone can help me with this?

**Comment by jeromevdl** [comment]
Using com.qualinsight.mojo.cobertura 1.1.0, cobertura 2.1.1, maven 3.3.9, JDK 1.8.0_45

The class not found is inside the same project and is not an inner class...

[WARNING] Unable to instrument file D:\workspace\PROJECT\target\classes\com\xxx\yyy\entity\dao\businessrules\UpdateMarketListRule.class
java.lang.RuntimeException: java.lang.ClassNotFoundException: com/xxx/yyy/marketfeed/exceptions/InvalidMarketIdException
        at net.sourceforge.cobertura.instrument.CoberturaClassWriter.getCommonSuperClass(CoberturaC lassWriter.java:35)
        at org.objectweb.asm.ClassWriter.a(Unknown Source)
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
        at org.objectweb.asm.util.CheckMethodAdapter.visitMaxs(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
        at org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:214)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:317)
        at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90)
        at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74)
        at com.qualinsight.mojo.cobertura.core.AbstractInstrumentationMojo.processInstrumentation(AbstractInstrumentationMojo.java:147)
        at com.qualinsight.mojo.cobertura.core.AbstractInstrumentationMojo.execute(AbstractInstrumentationMojo.java:88)
        at com.qualinsight.mojo.cobertura.core.UTInstrumentationMojo.execute(UTInstrumentationMojo.java:30)

**Comment by kenblog** [comment]
I'm using cobertura 2.1.1 and unable to  instrument file.
I tried to add auxClasspath, but the error still happen, did anyone met same issue and how to resolve it?
Thanks.

Below is the erro log:
[cobertura-instrument][WARN] Unable to  instrument file com.test.***.class
[cobertura-instrument] java.lang.RuntimeException: java.lang.ClassNotFoundException: com.test.***.class.
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaClassWriter.getCommonSuperClass(CoberturaClassWriter.java:35) ~[cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter.visitMaxs(Unknown Source) ~[asm-util-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(Unknown Source) ~[asm-commons-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-tree-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(Unknown Source) ~[asm-util-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(Unknown Source) ~[asm-util-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.1.jar:5.0.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:214) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:129) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:243) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentationToSingleClass(CodeInstrumentationTask.java:299) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.addInstrumentation(CodeInstrumentationTask.java:308) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.CodeInstrumentationTask.instrument(CodeInstrumentationTask.java:90) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.dsl.Cobertura.instrumentCode(Cobertura.java:74) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.InstrumentMain.instrument(InstrumentMain.java:82) [cobertura-2.1.1.jar:2.1.1]
[cobertura-instrument]  at net.sourceforge.cobertura.instrument.InstrumentMain.main(InstrumentMain.java:99) [cobertura-2.1.1.jar:2.1.1]
