### ISSUE TITLE
ParseException: Encountered " "{" "{ "" - this.new AnonymousClass

### ISSUE THREAD

**Issue by AlfonZ42** [cobertura/cobertura#53]
```
[cobertura-report] {DATETIME} net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
INFO: Cobertura: Loaded information on 3 classes.
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " "{" "{ "" at line 4, column 34.
Cobertura 2.0.3-SNAPSHOT - GNU GPL License (NO WARRANTY) - See COPYRIGHT file

Was expecting one of:
WARN   getAccumlatedCCNForSource, JavaNCSS got an error while parsing the java file .\src\Outer.java    "instanceof" ...
    ";" ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...

    "<=" ...ParseException in STDIN

    ">=" ...Last useful checkpoint: "OuterOuter.Outer()"

    "!=" ...Encountered " "{" "{ "" at line 4, column 34.

    "||" ...Was expecting one of:

    "&&" ...
    "instanceof" ...    "++" ...

    ";" ...    "--" ...

    "=" ...    "+" ...

    ">" ...    "-" ...

    "<" ...
    "*" ...    "?" ...

    "/" ...    "==" ...

    "&" ...    "<=" ...

    "|" ...    ">=" ...

    "^" ...
    "!=" ...    "%" ...

    "||" ...    "+=" ...

    "&&" ...    "-=" ...

    "++" ...    "*=" ...

    "--" ...
    "+" ...
    "/=" ...    "-" ...

    "&=" ...    "*" ...

    "|=" ...    "/" ...

    "^=" ...    "&" ...

    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...

    at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:11845)
    at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:11706)
    "|" ...
    at net.sourceforge.cobertura.javancss.parser.JavaParser.Statement(JavaParser.java:3705)    "^" ...

    at net.sourceforge.cobertura.javancss.parser.JavaParser.BlockStatement(JavaParser.java:3896)    "%" ...

    "+=" ...
    at net.sourceforge.cobertura.javancss.parser.JavaParser.ConstructorDeclaration(JavaParser.java:2311)    "-=" ...

    "*=" ...
    at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1010)    "/=" ...

    "&=" ...
    at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:874)    "|=" ...
    at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:801)

    at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:706)
    "^=" ...
    at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:555)    "%=" ...

    "<<=" ...
    at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:303)    ">>=" ...

    at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)    ">>>=" ...

    at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:192)    ">" ...


    at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:268)

Report time: 94ms
    at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:346)
    at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSource(ComplexityCalculator.java:105)
    at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
    at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:234)
    at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:201)
    at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:167)
    at net.sourceforge.cobertura.reporting.xml.XMLReport.<init>(XMLReport.java:67)
    at net.sourceforge.cobertura.reporting.Main.parseArguments(Main.java:106)
    at net.sourceforge.cobertura.reporting.Main.main(Main.java:169)
```

Source:

```
public class Outer {
    private Inner inner;
    public Outer() {
        inner = this.new Inner() {
            @Override
            public int getI() {
                return 15;
            }
        };
    }
    private class Inner {
        public int getI() {
            return 1;
        }
    }
}
```

**Comment by arvindram-kiwi** [comment]
waiting now
