### ISSUE TITLE
With 2.0.3 still seeing ClassNotFoundException in-spite of using --auxClasspath during instrumentation

### ISSUE THREAD

**Issue by wishabcd** [cobertura/cobertura#74]
Command Line used :- C:\cobertura-2.0.3\cobertura-instrument.bat --auxClasspath "c:\Program Files (x86)\XX\OIU\CLI\oiucli-1.0.0-jar-with-dependencies" --datafile  "c:\cc\SER\oiu_cli.ser" "c:\Program Files (x86)\XX\OIU\CLI"\oiucli-1.0.0-jar-with-dependencies\com

Sep 13, 2013 1:25:01 AM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
INFO: Cobertura: Loaded information on 40 classes.
Sep 13, 2013 1:25:02 AM net.sourceforge.cobertura.coveragedata.TouchCollector registerClass
SEVERE: Exception when registering class: com/xx/oiu/cli/OIUOption
java.lang.ClassNotFoundException: com.xx.oiu.cli.OIUOption
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.registerClass(TouchCollector.java:80)
        at com.xx.oiu.cli.OIUOption.__cobertura_init(OIUOption.java)
        at com.xx.oiu.cli.OIUOption.<clinit>(OIUOption.java)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at net.sourceforge.cobertura.instrument.CoberturaClassWriter.getCommonSuperClass(CoberturaClassWriter.java:32)
        at org.objectweb.asm.ClassWriter.a(Unknown Source)
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
        at org.objectweb.asm.util.CheckMethodAdapter.visitMaxs(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitMaxs(Unknown Source)
        at org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:205)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:316)
        at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
        at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)

**Comment by dennisl** [comment]
The latest SNAPSHOT version is available from here:
https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/cobertura/

**Comment by dennisl** [comment]
Cobertura 2.1.1 has been released. Can someone please try with that version.

**Comment by progosch** [comment]
Hi Dennis. Thanks it works well for us.

**Comment by wu560130911** [comment]
hi Dennis,use cobertura 2.1.1 but also have this issues.

`Caused by: java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector
	at com.netease.payments.bank.spdb.SpdbQuickPayPayGateSnStrategyBankService.__cobertura_init(SpdbQuickPayPayGateSnStrategyBankService.java)
	at com.netease.payments.bank.spdb.SpdbQuickPayPayGateSnStrategyBankService.<clinit>(SpdbQuickPayPayGateSnStrategyBankService.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at com.netease.payments.bank.factory.loader.hotswap.LocalHotswapBankServiceLoader.loadBankServiceClassImpl(LocalHotswapBankServiceLoader.java:236)`

**Comment by wu560130911** [comment]
use in custom classloader
