### ISSUE TITLE
cobertura 2.0.3: java.lang.RuntimeException: JSR/RET are not supported with computeFrames option

### ISSUE THREAD

**Issue by oosterholt** [cobertura/cobertura#93]
When instrumenting my classes I run into this exception:

```
WARN   instrumentClass, Unable to instrument file /PATH-TO-CLASS/MyClass.class
java.lang.RuntimeException: JSR/RET are not supported with computeFrames option
java.lang.RuntimeException: JSR/RET are not supported with computeFrames option
    at org.objectweb.asm.Frame.a(Unknown Source)
    at org.objectweb.asm.MethodWriter.visitJumpInsn(Unknown Source)
    at org.objectweb.asm.MethodVisitor.visitJumpInsn(Unknown Source)
    at org.objectweb.asm.util.CheckMethodAdapter.visitJumpInsn(Unknown Source)
    at org.objectweb.asm.MethodVisitor.visitJumpInsn(Unknown Source)
    at org.objectweb.asm.MethodVisitor.visitJumpInsn(Unknown Source)
    at net.sourceforge.cobertura.instrument.FindTouchPointsMethodAdapter.visitJumpInsn(FindTouchPointsMethodAdapter.java:250)
    at org.objectweb.asm.MethodVisitor.visitJumpInsn(Unknown Source)
    at org.objectweb.asm.tree.JumpInsnNode.accept(Unknown Source)
    at org.objectweb.asm.tree.InsnList.accept(Unknown Source)
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
    at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(Unknown Source)
    at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
    at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(Unknown Source)
    at org.objectweb.asm.ClassReader.b(Unknown Source)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:205)
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
    at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
    at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
    at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
    at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
    at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)
```

What can I do to fix this?

**Comment by chestnutt** [comment]
Issue still exists in version 2.1.1. Possibly because our jar file has to be built for java 1.5?

**Comment by dennisl** [comment]
@chestnutt That will be difficult to solve, since Cobertura 2.1.1+ requires Java 6. The solution would vary, depending on your build system.

**Comment by chestnutt** [comment]
yep, that would be a problem. Thanks for pointing that out.
