### ISSUE TITLE
No coverage reported when using PowerMock

### ISSUE THREAD

**Issue by hashbrown** [cobertura/cobertura#94]
With 2.0.3:  Root cause is apparently related to issue#25.  For any test that I use with a PowerMock runner of junit rule, using `forkMode="perTest"` I get the following error at the end of the test:

```
[junit] Exception in thread "Thread-1" java.lang.ExceptionInInitializerError
[junit]     at com.ettex.rialto.utils.collections.LinkedList$ListElement.__cobertura_init(LinkedList.java)
[junit]     at com.ettex.rialto.utils.collections.LinkedList$ListElement.<clinit>(LinkedList.java)
[junit]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[junit]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[junit]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[junit]     at java.lang.reflect.Method.invoke(Method.java:601)
[junit]     at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:120)
[junit]     at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:106)
[junit]     at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:270)
[junit]     at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:32)
[junit]     at java.lang.Thread.run(Thread.java:722)
[junit] Caused by: java.lang.IllegalStateException: Shutdown in progress
[junit]     at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
[junit]     at java.lang.Runtime.addShutdownHook(Runtime.java:209)
[junit]     at net.sourceforge.cobertura.coveragedata.ProjectData.initialize(ProjectData.java:237)
[junit]     at net.sourceforge.cobertura.coveragedata.ProjectData.getGlobalProjectData(ProjectData.java:208)
[junit]     at net.sourceforge.cobertura.coveragedata.TouchCollector.<clinit>(TouchCollector.java:46)
[junit]     ... 11 more
```

 That test then has no coverage reported.  The class and methods exist in coverage.xml, but have no interactions reported.

If I run the tests using `forkMode="once"` then I do not get the issue.  Unfortunately that mode causes all sorts of classloader issues with PowerMock, so its not a realistic solution.

**Comment by tomacla** [comment]
hello. facing the same issue. is there a fix planned for this ?
thanks

**Comment by GoGoris** [comment]
I thought this issue was fixed a long time ago, but with the newest release of cobertura I am still having this issue. forkmode=pertest/once didn't work, explicitely adding the dependencies neither (cobertura-maven-plugin:2.7 uses the latest version anyway) IS this a new issue?
I only have 0% coverage on classes that use PowerMockito, like the OP.

**Comment by RonanOD** [comment]
+1 to previous comment. 0% coverage if using Powermockito

**Comment by jjNford** [comment]
Any progress or information on this?

**Comment by boardbloke** [comment]
+1 - this is a pain when using Cobertura and Spock together because Spock I have to resort to PowerMock when mocking java static methods.

**Comment by msiemczyk** [comment]
Unfortunately I see same thing with EasyMock...I was forced to use the PowerMock because one method was "final" and I'm not able to change it. Is there any chance for fix to this?
