### ISSUE TITLE
Cobertura issue in java7 :: Exception in thread "Thread-1" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by sksumit1** [cobertura/cobertura#99]
My testng unit tests running with ANT generate very good cobertura code coverage report. But on up-gradation from java1.6 to java1.7 and using cobertura2.0.3, i have started to get the below error. I looked into the comment http://sourceforge.net/mailarchive/message.php?msg_id=31424355. Still i am getting the issue. Any suggestions?

[testng] Exception in thread "Thread-1" java.lang.ExceptionInInitializerError
   [testng]     at org.my.code.MyFile.__cobertura_init(MyFile.java)
   [testng]     at org.my.code.MyFile.<clinit>(MyFile.java)
   [testng]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   [testng]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng]     at java.lang.reflect.Method.invoke(Method.java:601)
   [testng]     at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToSingleClassOnProjectData(TouchCollector.java:121)
   [testng]     at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnProjectData(TouchCollector.java:107)
   [testng]     at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectData(ProjectData.java:272)
   [testng]     at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:33)
   [testng]     at java.lang.Thread.run(Thread.java:722)
   [testng] Caused by: java.lang.IllegalStateException: Shutdown in progress
   [testng]     at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
   [testng]     at java.lang.Runtime.addShutdownHook(Runtime.java:209)
   [testng]     at net.sourceforge.cobertura.coveragedata.ProjectData.initialize(ProjectData.java:239)
   [testng]     at net.sourceforge.cobertura.coveragedata.ProjectData.getGlobalProjectData(ProjectData.java:209)
   [testng]     at net.sourceforge.cobertura.coveragedata.TouchCollector.<clinit>(TouchCollector.java:46)
   [testng]     ... 11 more
cb.html:
[cobertura-report] The jvmargs attribute is deprecated. Please use nested jvmarg elements.

**Comment by thakur-richa15** [comment]
I had the same issue using Java 1.6, Cobertrua 2.0.3, Powermock 1.4.8.
I upgraded the PowerMock to 1.5.4.
It solved the issue.
Thanks!!
